// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.1
// source: spanner.proto

package spannerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State of the Tree.
// Mirrors trillian.TreeState.
type TreeState int32

const (
	TreeState_UNKNOWN_TREE_STATE TreeState = 0
	TreeState_ACTIVE             TreeState = 1
	TreeState_FROZEN             TreeState = 2
)

// Enum value maps for TreeState.
var (
	TreeState_name = map[int32]string{
		0: "UNKNOWN_TREE_STATE",
		1: "ACTIVE",
		2: "FROZEN",
	}
	TreeState_value = map[string]int32{
		"UNKNOWN_TREE_STATE": 0,
		"ACTIVE":             1,
		"FROZEN":             2,
	}
)

func (x TreeState) Enum() *TreeState {
	p := new(TreeState)
	*p = x
	return p
}

func (x TreeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TreeState) Descriptor() protoreflect.EnumDescriptor {
	return file_spanner_proto_enumTypes[0].Descriptor()
}

func (TreeState) Type() protoreflect.EnumType {
	return &file_spanner_proto_enumTypes[0]
}

func (x TreeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TreeState.Descriptor instead.
func (TreeState) EnumDescriptor() ([]byte, []int) {
	return file_spanner_proto_rawDescGZIP(), []int{0}
}

// Type of the Tree.
// Mirrors trillian.TreeType.
type TreeType int32

const (
	TreeType_UNKNOWN        TreeType = 0
	TreeType_LOG            TreeType = 1
	TreeType_PREORDERED_LOG TreeType = 3
)

// Enum value maps for TreeType.
var (
	TreeType_name = map[int32]string{
		0: "UNKNOWN",
		1: "LOG",
		3: "PREORDERED_LOG",
	}
	TreeType_value = map[string]int32{
		"UNKNOWN":        0,
		"LOG":            1,
		"PREORDERED_LOG": 3,
	}
)

func (x TreeType) Enum() *TreeType {
	p := new(TreeType)
	*p = x
	return p
}

func (x TreeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TreeType) Descriptor() protoreflect.EnumDescriptor {
	return file_spanner_proto_enumTypes[1].Descriptor()
}

func (TreeType) Type() protoreflect.EnumType {
	return &file_spanner_proto_enumTypes[1]
}

func (x TreeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TreeType.Descriptor instead.
func (TreeType) EnumDescriptor() ([]byte, []int) {
	return file_spanner_proto_rawDescGZIP(), []int{1}
}

// Defines the preimage protection used for tree leaves / nodes.
// Eg, RFC6962 dictates a 0x00 prefix for leaves and 0x01 for nodes.
// Mirrors trillian.HashStrategy.
type HashStrategy int32

const (
	HashStrategy_UNKNOWN_HASH_STRATEGY HashStrategy = 0
	HashStrategy_RFC_6962              HashStrategy = 1
	HashStrategy_TEST_MAP_HASHER       HashStrategy = 2
	HashStrategy_OBJECT_RFC6962_SHA256 HashStrategy = 3
	HashStrategy_CONIKS_SHA512_256     HashStrategy = 4
	HashStrategy_CONIKS_SHA256         HashStrategy = 5
)

// Enum value maps for HashStrategy.
var (
	HashStrategy_name = map[int32]string{
		0: "UNKNOWN_HASH_STRATEGY",
		1: "RFC_6962",
		2: "TEST_MAP_HASHER",
		3: "OBJECT_RFC6962_SHA256",
		4: "CONIKS_SHA512_256",
		5: "CONIKS_SHA256",
	}
	HashStrategy_value = map[string]int32{
		"UNKNOWN_HASH_STRATEGY": 0,
		"RFC_6962":              1,
		"TEST_MAP_HASHER":       2,
		"OBJECT_RFC6962_SHA256": 3,
		"CONIKS_SHA512_256":     4,
		"CONIKS_SHA256":         5,
	}
)

func (x HashStrategy) Enum() *HashStrategy {
	p := new(HashStrategy)
	*p = x
	return p
}

func (x HashStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_spanner_proto_enumTypes[2].Descriptor()
}

func (HashStrategy) Type() protoreflect.EnumType {
	return &file_spanner_proto_enumTypes[2]
}

func (x HashStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashStrategy.Descriptor instead.
func (HashStrategy) EnumDescriptor() ([]byte, []int) {
	return file_spanner_proto_rawDescGZIP(), []int{2}
}

// Supported hash algorithms.
// The numbering space is the same as for TLS, given in RFC 5246 s7.4.1.4.1. See
// http://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-18.
// Mirrors trillian.HashAlgorithm.
type HashAlgorithm int32

const (
	// No hash algorithm is used.
	HashAlgorithm_NONE HashAlgorithm = 0
	// SHA256 is used.
	HashAlgorithm_SHA256 HashAlgorithm = 4
)

// Enum value maps for HashAlgorithm.
var (
	HashAlgorithm_name = map[int32]string{
		0: "NONE",
		4: "SHA256",
	}
	HashAlgorithm_value = map[string]int32{
		"NONE":   0,
		"SHA256": 4,
	}
)

func (x HashAlgorithm) Enum() *HashAlgorithm {
	p := new(HashAlgorithm)
	*p = x
	return p
}

func (x HashAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_spanner_proto_enumTypes[3].Descriptor()
}

func (HashAlgorithm) Type() protoreflect.EnumType {
	return &file_spanner_proto_enumTypes[3]
}

func (x HashAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashAlgorithm.Descriptor instead.
func (HashAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_spanner_proto_rawDescGZIP(), []int{3}
}

// Supported signature algorithms.
// The numbering space is the same as for TLS, given in RFC 5246 s7.4.1.4.1. See
// http://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-16.
// Mirrors trillian.SignatureAlgorithm.
type SignatureAlgorithm int32

const (
	// Anonymous signature scheme.
	SignatureAlgorithm_ANONYMOUS SignatureAlgorithm = 0
	// RSA signature scheme.
	SignatureAlgorithm_RSA SignatureAlgorithm = 1
	// ECDSA signature scheme.
	SignatureAlgorithm_ECDSA SignatureAlgorithm = 3
)

// Enum value maps for SignatureAlgorithm.
var (
	SignatureAlgorithm_name = map[int32]string{
		0: "ANONYMOUS",
		1: "RSA",
		3: "ECDSA",
	}
	SignatureAlgorithm_value = map[string]int32{
		"ANONYMOUS": 0,
		"RSA":       1,
		"ECDSA":     3,
	}
)

func (x SignatureAlgorithm) Enum() *SignatureAlgorithm {
	p := new(SignatureAlgorithm)
	*p = x
	return p
}

func (x SignatureAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignatureAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_spanner_proto_enumTypes[4].Descriptor()
}

func (SignatureAlgorithm) Type() protoreflect.EnumType {
	return &file_spanner_proto_enumTypes[4]
}

func (x SignatureAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignatureAlgorithm.Descriptor instead.
func (SignatureAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_spanner_proto_rawDescGZIP(), []int{4}
}

// LogStorageConfig holds settings which tune the storage implementation for
// a given log tree.
type LogStorageConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// num_unseq_buckets defines the length of the unsequenced time ring buffer.
	// This value must *never* be reduced for any provisioned tree.
	//
	// This value should be >= 1, and there's probably not much benefit in
	// raising it past about 4.
	// TODO(al): test what the effects of various values are here.
	NumUnseqBuckets int64 `protobuf:"varint,1,opt,name=num_unseq_buckets,json=numUnseqBuckets,proto3" json:"num_unseq_buckets,omitempty"`
	// num_merkle_buckets defines the number of individual buckets below each
	// unsequenced ring bucket.
	// This value may be changed at any time (so long as you understand the
	// impact it'll have on integration performace!)
	//
	// This value must lie in the range [1..256]
	NumMerkleBuckets int64 `protobuf:"varint,2,opt,name=num_merkle_buckets,json=numMerkleBuckets,proto3" json:"num_merkle_buckets,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogStorageConfig) Reset() {
	*x = LogStorageConfig{}
	mi := &file_spanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStorageConfig) ProtoMessage() {}

func (x *LogStorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_spanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStorageConfig.ProtoReflect.Descriptor instead.
func (*LogStorageConfig) Descriptor() ([]byte, []int) {
	return file_spanner_proto_rawDescGZIP(), []int{0}
}

func (x *LogStorageConfig) GetNumUnseqBuckets() int64 {
	if x != nil {
		return x.NumUnseqBuckets
	}
	return 0
}

func (x *LogStorageConfig) GetNumMerkleBuckets() int64 {
	if x != nil {
		return x.NumMerkleBuckets
	}
	return 0
}

// MapStorageConfig holds settings which tune the storage implementation for
// a given map tree.
type MapStorageConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapStorageConfig) Reset() {
	*x = MapStorageConfig{}
	mi := &file_spanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapStorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapStorageConfig) ProtoMessage() {}

func (x *MapStorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_spanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapStorageConfig.ProtoReflect.Descriptor instead.
func (*MapStorageConfig) Descriptor() ([]byte, []int) {
	return file_spanner_proto_rawDescGZIP(), []int{1}
}

// TreeInfo stores information about a Trillian tree.
type TreeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tree_id is the ID of the tree, and is used as a primary key.
	TreeId int64 `protobuf:"varint,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	// key_id identifies the private key associated with this tree.
	KeyId int64 `protobuf:"varint,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// name is a short name for this tree.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// description is a short free form text describing the tree.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// tree_type identifies whether this is a Log or a Map tree.
	TreeType TreeType `protobuf:"varint,5,opt,name=tree_type,json=treeType,proto3,enum=spannerpb.TreeType" json:"tree_type,omitempty"`
	// tree_state is the state of the tree.
	TreeState TreeState `protobuf:"varint,8,opt,name=tree_state,json=treeState,proto3,enum=spannerpb.TreeState" json:"tree_state,omitempty"`
	// hash_strategy is the hashing strategy used by the tree.
	HashStrategy HashStrategy `protobuf:"varint,9,opt,name=hash_strategy,json=hashStrategy,proto3,enum=spannerpb.HashStrategy" json:"hash_strategy,omitempty"`
	// hash_algorithm is the hash algorithm used by the tree.
	HashAlgorithm HashAlgorithm `protobuf:"varint,10,opt,name=hash_algorithm,json=hashAlgorithm,proto3,enum=spannerpb.HashAlgorithm" json:"hash_algorithm,omitempty"`
	// signature_algorithm is the signature algorithm used by the tree.
	SignatureAlgorithm SignatureAlgorithm `protobuf:"varint,11,opt,name=signature_algorithm,json=signatureAlgorithm,proto3,enum=spannerpb.SignatureAlgorithm" json:"signature_algorithm,omitempty"`
	// create_time_nanos is the creation timestamp of the tree, in nanos since
	// epoch.
	CreateTimeNanos int64 `protobuf:"varint,13,opt,name=create_time_nanos,json=createTimeNanos,proto3" json:"create_time_nanos,omitempty"`
	// update_time_nanos is the last update time of the tree, in nanos since
	// epoch.
	UpdateTimeNanos int64 `protobuf:"varint,14,opt,name=update_time_nanos,json=updateTimeNanos,proto3" json:"update_time_nanos,omitempty"`
	// private_key should be used to generate signatures for this tree.
	PrivateKey *anypb.Any `protobuf:"bytes,15,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// public_key_der should be used to verify signatures produced by this tree.
	// It is the key in DER-encoded PKIX form.
	PublicKeyDer []byte `protobuf:"bytes,16,opt,name=public_key_der,json=publicKeyDer,proto3" json:"public_key_der,omitempty"`
	// config contains the log or map specific tree configuration.
	//
	// Types that are valid to be assigned to StorageConfig:
	//
	//	*TreeInfo_LogStorageConfig
	//	*TreeInfo_MapStorageConfig
	StorageConfig isTreeInfo_StorageConfig `protobuf_oneof:"storage_config"`
	// max_root_duration_millis is the interval after which a new signed root is
	// produced even if there have been no submission.  If zero, this behavior is
	// disabled.
	MaxRootDurationMillis int64 `protobuf:"varint,17,opt,name=max_root_duration_millis,json=maxRootDurationMillis,proto3" json:"max_root_duration_millis,omitempty"`
	// If true the tree was soft deleted.
	Deleted bool `protobuf:"varint,18,opt,name=deleted,proto3" json:"deleted,omitempty"`
	// Time of tree deletion, if any.
	DeleteTimeNanos int64 `protobuf:"varint,19,opt,name=delete_time_nanos,json=deleteTimeNanos,proto3" json:"delete_time_nanos,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TreeInfo) Reset() {
	*x = TreeInfo{}
	mi := &file_spanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeInfo) ProtoMessage() {}

func (x *TreeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeInfo.ProtoReflect.Descriptor instead.
func (*TreeInfo) Descriptor() ([]byte, []int) {
	return file_spanner_proto_rawDescGZIP(), []int{2}
}

func (x *TreeInfo) GetTreeId() int64 {
	if x != nil {
		return x.TreeId
	}
	return 0
}

func (x *TreeInfo) GetKeyId() int64 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *TreeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TreeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TreeInfo) GetTreeType() TreeType {
	if x != nil {
		return x.TreeType
	}
	return TreeType_UNKNOWN
}

func (x *TreeInfo) GetTreeState() TreeState {
	if x != nil {
		return x.TreeState
	}
	return TreeState_UNKNOWN_TREE_STATE
}

func (x *TreeInfo) GetHashStrategy() HashStrategy {
	if x != nil {
		return x.HashStrategy
	}
	return HashStrategy_UNKNOWN_HASH_STRATEGY
}

func (x *TreeInfo) GetHashAlgorithm() HashAlgorithm {
	if x != nil {
		return x.HashAlgorithm
	}
	return HashAlgorithm_NONE
}

func (x *TreeInfo) GetSignatureAlgorithm() SignatureAlgorithm {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return SignatureAlgorithm_ANONYMOUS
}

func (x *TreeInfo) GetCreateTimeNanos() int64 {
	if x != nil {
		return x.CreateTimeNanos
	}
	return 0
}

func (x *TreeInfo) GetUpdateTimeNanos() int64 {
	if x != nil {
		return x.UpdateTimeNanos
	}
	return 0
}

func (x *TreeInfo) GetPrivateKey() *anypb.Any {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *TreeInfo) GetPublicKeyDer() []byte {
	if x != nil {
		return x.PublicKeyDer
	}
	return nil
}

func (x *TreeInfo) GetStorageConfig() isTreeInfo_StorageConfig {
	if x != nil {
		return x.StorageConfig
	}
	return nil
}

func (x *TreeInfo) GetLogStorageConfig() *LogStorageConfig {
	if x != nil {
		if x, ok := x.StorageConfig.(*TreeInfo_LogStorageConfig); ok {
			return x.LogStorageConfig
		}
	}
	return nil
}

func (x *TreeInfo) GetMapStorageConfig() *MapStorageConfig {
	if x != nil {
		if x, ok := x.StorageConfig.(*TreeInfo_MapStorageConfig); ok {
			return x.MapStorageConfig
		}
	}
	return nil
}

func (x *TreeInfo) GetMaxRootDurationMillis() int64 {
	if x != nil {
		return x.MaxRootDurationMillis
	}
	return 0
}

func (x *TreeInfo) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *TreeInfo) GetDeleteTimeNanos() int64 {
	if x != nil {
		return x.DeleteTimeNanos
	}
	return 0
}

type isTreeInfo_StorageConfig interface {
	isTreeInfo_StorageConfig()
}

type TreeInfo_LogStorageConfig struct {
	LogStorageConfig *LogStorageConfig `protobuf:"bytes,6,opt,name=log_storage_config,json=logStorageConfig,proto3,oneof"`
}

type TreeInfo_MapStorageConfig struct {
	MapStorageConfig *MapStorageConfig `protobuf:"bytes,7,opt,name=map_storage_config,json=mapStorageConfig,proto3,oneof"`
}

func (*TreeInfo_LogStorageConfig) isTreeInfo_StorageConfig() {}

func (*TreeInfo_MapStorageConfig) isTreeInfo_StorageConfig() {}

// TreeHead is the storage format for Trillian's commitment to a particular
// tree state.
type TreeHead struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tree_id identifies the tree this TreeHead is built from.
	TreeId int64 `protobuf:"varint,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	// ts_nanos is the nanosecond resolution timestamp at which the
	// TreeHead was created.
	TsNanos int64 `protobuf:"varint,2,opt,name=ts_nanos,json=tsNanos,proto3" json:"ts_nanos,omitempty"`
	// tree_size is the number of entries in the tree.
	TreeSize int64 `protobuf:"varint,3,opt,name=tree_size,json=treeSize,proto3" json:"tree_size,omitempty"`
	// root_hash is the root of the tree.
	RootHash []byte `protobuf:"bytes,4,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	// signature holds the raw digital signature across the serialized log_root
	// (not present) represented by the data in this TreeHead.
	Signature []byte `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	// tree_revision identifies the revision at which the TreeHead was created.
	TreeRevision  int64  `protobuf:"varint,6,opt,name=tree_revision,json=treeRevision,proto3" json:"tree_revision,omitempty"`
	Metadata      []byte `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeHead) Reset() {
	*x = TreeHead{}
	mi := &file_spanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeHead) ProtoMessage() {}

func (x *TreeHead) ProtoReflect() protoreflect.Message {
	mi := &file_spanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeHead.ProtoReflect.Descriptor instead.
func (*TreeHead) Descriptor() ([]byte, []int) {
	return file_spanner_proto_rawDescGZIP(), []int{3}
}

func (x *TreeHead) GetTreeId() int64 {
	if x != nil {
		return x.TreeId
	}
	return 0
}

func (x *TreeHead) GetTsNanos() int64 {
	if x != nil {
		return x.TsNanos
	}
	return 0
}

func (x *TreeHead) GetTreeSize() int64 {
	if x != nil {
		return x.TreeSize
	}
	return 0
}

func (x *TreeHead) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *TreeHead) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TreeHead) GetTreeRevision() int64 {
	if x != nil {
		return x.TreeRevision
	}
	return 0
}

func (x *TreeHead) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_spanner_proto protoreflect.FileDescriptor

const file_spanner_proto_rawDesc = "" +
	"\n" +
	"\rspanner.proto\x12\tspannerpb\x1a\x19google/protobuf/any.proto\"l\n" +
	"\x10LogStorageConfig\x12*\n" +
	"\x11num_unseq_buckets\x18\x01 \x01(\x03R\x0fnumUnseqBuckets\x12,\n" +
	"\x12num_merkle_buckets\x18\x02 \x01(\x03R\x10numMerkleBuckets\"\x12\n" +
	"\x10MapStorageConfig\"\x8c\a\n" +
	"\bTreeInfo\x12\x17\n" +
	"\atree_id\x18\x01 \x01(\x03R\x06treeId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\x03R\x05keyId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x120\n" +
	"\ttree_type\x18\x05 \x01(\x0e2\x13.spannerpb.TreeTypeR\btreeType\x123\n" +
	"\n" +
	"tree_state\x18\b \x01(\x0e2\x14.spannerpb.TreeStateR\ttreeState\x12<\n" +
	"\rhash_strategy\x18\t \x01(\x0e2\x17.spannerpb.HashStrategyR\fhashStrategy\x12?\n" +
	"\x0ehash_algorithm\x18\n" +
	" \x01(\x0e2\x18.spannerpb.HashAlgorithmR\rhashAlgorithm\x12N\n" +
	"\x13signature_algorithm\x18\v \x01(\x0e2\x1d.spannerpb.SignatureAlgorithmR\x12signatureAlgorithm\x12*\n" +
	"\x11create_time_nanos\x18\r \x01(\x03R\x0fcreateTimeNanos\x12*\n" +
	"\x11update_time_nanos\x18\x0e \x01(\x03R\x0fupdateTimeNanos\x125\n" +
	"\vprivate_key\x18\x0f \x01(\v2\x14.google.protobuf.AnyR\n" +
	"privateKey\x12$\n" +
	"\x0epublic_key_der\x18\x10 \x01(\fR\fpublicKeyDer\x12K\n" +
	"\x12log_storage_config\x18\x06 \x01(\v2\x1b.spannerpb.LogStorageConfigH\x00R\x10logStorageConfig\x12K\n" +
	"\x12map_storage_config\x18\a \x01(\v2\x1b.spannerpb.MapStorageConfigH\x00R\x10mapStorageConfig\x127\n" +
	"\x18max_root_duration_millis\x18\x11 \x01(\x03R\x15maxRootDurationMillis\x12\x18\n" +
	"\adeleted\x18\x12 \x01(\bR\adeleted\x12*\n" +
	"\x11delete_time_nanos\x18\x13 \x01(\x03R\x0fdeleteTimeNanosB\x10\n" +
	"\x0estorage_configJ\x04\b\f\x10\r\"\xe9\x01\n" +
	"\bTreeHead\x12\x17\n" +
	"\atree_id\x18\x01 \x01(\x03R\x06treeId\x12\x19\n" +
	"\bts_nanos\x18\x02 \x01(\x03R\atsNanos\x12\x1b\n" +
	"\ttree_size\x18\x03 \x01(\x03R\btreeSize\x12\x1b\n" +
	"\troot_hash\x18\x04 \x01(\fR\brootHash\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\fR\tsignature\x12#\n" +
	"\rtree_revision\x18\x06 \x01(\x03R\ftreeRevision\x12\x1a\n" +
	"\bmetadata\x18\t \x01(\fR\bmetadataJ\x04\b\x05\x10\x06J\x04\b\b\x10\tJ\x04\b\a\x10\b*;\n" +
	"\tTreeState\x12\x16\n" +
	"\x12UNKNOWN_TREE_STATE\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\n" +
	"\n" +
	"\x06FROZEN\x10\x02*?\n" +
	"\bTreeType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03LOG\x10\x01\x12\x12\n" +
	"\x0ePREORDERED_LOG\x10\x03\"\x04\b\x02\x10\x02*\x03MAP*\x91\x01\n" +
	"\fHashStrategy\x12\x19\n" +
	"\x15UNKNOWN_HASH_STRATEGY\x10\x00\x12\f\n" +
	"\bRFC_6962\x10\x01\x12\x13\n" +
	"\x0fTEST_MAP_HASHER\x10\x02\x12\x19\n" +
	"\x15OBJECT_RFC6962_SHA256\x10\x03\x12\x15\n" +
	"\x11CONIKS_SHA512_256\x10\x04\x12\x11\n" +
	"\rCONIKS_SHA256\x10\x05*%\n" +
	"\rHashAlgorithm\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06SHA256\x10\x04*7\n" +
	"\x12SignatureAlgorithm\x12\r\n" +
	"\tANONYMOUS\x10\x00\x12\a\n" +
	"\x03RSA\x10\x01\x12\t\n" +
	"\x05ECDSA\x10\x03B;Z9github.com/google/trillian/storage/cloudspanner/spannerpbb\x06proto3"

var (
	file_spanner_proto_rawDescOnce sync.Once
	file_spanner_proto_rawDescData []byte
)

func file_spanner_proto_rawDescGZIP() []byte {
	file_spanner_proto_rawDescOnce.Do(func() {
		file_spanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spanner_proto_rawDesc), len(file_spanner_proto_rawDesc)))
	})
	return file_spanner_proto_rawDescData
}

var file_spanner_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_spanner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_spanner_proto_goTypes = []any{
	(TreeState)(0),           // 0: spannerpb.TreeState
	(TreeType)(0),            // 1: spannerpb.TreeType
	(HashStrategy)(0),        // 2: spannerpb.HashStrategy
	(HashAlgorithm)(0),       // 3: spannerpb.HashAlgorithm
	(SignatureAlgorithm)(0),  // 4: spannerpb.SignatureAlgorithm
	(*LogStorageConfig)(nil), // 5: spannerpb.LogStorageConfig
	(*MapStorageConfig)(nil), // 6: spannerpb.MapStorageConfig
	(*TreeInfo)(nil),         // 7: spannerpb.TreeInfo
	(*TreeHead)(nil),         // 8: spannerpb.TreeHead
	(*anypb.Any)(nil),        // 9: google.protobuf.Any
}
var file_spanner_proto_depIdxs = []int32{
	1, // 0: spannerpb.TreeInfo.tree_type:type_name -> spannerpb.TreeType
	0, // 1: spannerpb.TreeInfo.tree_state:type_name -> spannerpb.TreeState
	2, // 2: spannerpb.TreeInfo.hash_strategy:type_name -> spannerpb.HashStrategy
	3, // 3: spannerpb.TreeInfo.hash_algorithm:type_name -> spannerpb.HashAlgorithm
	4, // 4: spannerpb.TreeInfo.signature_algorithm:type_name -> spannerpb.SignatureAlgorithm
	9, // 5: spannerpb.TreeInfo.private_key:type_name -> google.protobuf.Any
	5, // 6: spannerpb.TreeInfo.log_storage_config:type_name -> spannerpb.LogStorageConfig
	6, // 7: spannerpb.TreeInfo.map_storage_config:type_name -> spannerpb.MapStorageConfig
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_spanner_proto_init() }
func file_spanner_proto_init() {
	if File_spanner_proto != nil {
		return
	}
	file_spanner_proto_msgTypes[2].OneofWrappers = []any{
		(*TreeInfo_LogStorageConfig)(nil),
		(*TreeInfo_MapStorageConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spanner_proto_rawDesc), len(file_spanner_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spanner_proto_goTypes,
		DependencyIndexes: file_spanner_proto_depIdxs,
		EnumInfos:         file_spanner_proto_enumTypes,
		MessageInfos:      file_spanner_proto_msgTypes,
	}.Build()
	File_spanner_proto = out.File
	file_spanner_proto_goTypes = nil
	file_spanner_proto_depIdxs = nil
}
