apiVersion: v1
kind: ConfigMap
metadata:
  name: trillian-tree
  namespace: createtree
data:
  __placeholder: |
    ###################################################################
    # Just a placeholder so that reapplying this won't overwrite treeID
    # if it already exists. This caused grief, do not remove.
    ###################################################################

