version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: monthly
  groups:
    go-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  groups:
    github-actions-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directories:
    - /examples/deployment/docker/db_server
    - /examples/deployment/docker/db_server/postgresql
    - /examples/deployment/docker/envsubst
    - /examples/deployment/docker/log_server
    - /examples/deployment/docker/log_signer
    - /examples/deployment/kubernetes/mysql/image
    - /integration/cloudbuild/testbase
  schedule:
    interval: monthly
  ignore:
    - dependency-name: "mysql"
      versions: [">= 9.0"]
  groups:
    docker-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: npm
  directory: /scripts/gcb2slack
  schedule:
    interval: monthly
