run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 90s
  skip-files:
    - types/internal/tls/tls.go

linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    # TODO(mhutchinson): lower this again after reworking interceptor
    min-complexity: 26
  depguard:
    list-type: blacklist
    packages:
      - golang.org/x/net/context
      - github.com/gogo/protobuf/proto

issues:
  # Don't turn off any checks by default. We can do this explicitly if needed.
  exclude-use-default: false

  exclude-rules:
    # The following grpc linters are excluded because grpc.Dial, grpc.DialContext and grpc.WithBlock will be supported throughout 1.x.
    - linters: [staticcheck]
      text: 'SA1019: grpc.Dial is deprecated: use NewClient instead'
    - linters: [staticcheck]
      text: 'SA1019: grpc.DialContext is deprecated: use NewClient instead'
    - linters: [staticcheck]
      text: 'SA1019: grpc.WithBlock is deprecated: this DialOption is not supported by NewClient'
