timeout: 1200s
substitutions:
  _MYSQL_TAG: "5.7"
steps:
- id: pull_mysql
  name : gcr.io/cloud-builders/docker
  args:
  - pull
  - marketplace.gcr.io/google/mysql5:${_MYSQL_TAG}
- id: tag_mysql
  name: gcr.io/cloud-builders/docker
  args:
  - tag
  - marketplace.gcr.io/google/mysql5:${_MYSQL_TAG}
  - gcr.io/${PROJECT_ID}/mysql5:${_MYSQL_TAG}
  waitFor:
  - pull_mysql
- id: build_db_server
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - --file=examples/deployment/docker/db_server/Dockerfile
  - --tag=gcr.io/${PROJECT_ID}/db_server:${COMMIT_SHA}
  - .
  waitFor:
  - tag_mysql
- id: build_log_server
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - --file=examples/deployment/docker/log_server/Dockerfile
  - --tag=gcr.io/${PROJECT_ID}/log_server:${COMMIT_SHA}
  - .
  waitFor: ["-"]
- id: build_log_signer
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - --file=examples/deployment/docker/log_signer/Dockerfile
  - --tag=gcr.io/${PROJECT_ID}/log_signer:${COMMIT_SHA}
  - .
  waitFor: ["-"]
- id: build_map_server
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - --file=examples/deployment/docker/map_server/Dockerfile
  - --tag=gcr.io/${PROJECT_ID}/map_server:${COMMIT_SHA}
  - .
  waitFor: ["-"]
images:
- gcr.io/${PROJECT_ID}/db_server:${COMMIT_SHA}
- gcr.io/${PROJECT_ID}/log_server:${COMMIT_SHA}
- gcr.io/${PROJECT_ID}/log_signer:${COMMIT_SHA}
- gcr.io/${PROJECT_ID}/map_server:${COMMIT_SHA}
