timeout: 900s
substitutions:
  _CLUSTER_NAME: trillian-opensource-ci
  _MASTER_ZONE: us-central1-a
  _CONFIG_MAP: examples/deployment/kubernetes/trillian-opensource-ci.yaml
  _MYSQL_TAG: "5.7"
steps:
- id: pull_mysql
  name : gcr.io/cloud-builders/docker
  args:
  - pull
  - marketplace.gcr.io/google/mysql5:${_MYSQL_TAG}
- id: tag_mysql
  name: gcr.io/cloud-builders/docker
  args:
  - tag
  - marketplace.gcr.io/google/mysql5:${_MYSQL_TAG}
  - gcr.io/${PROJECT_ID}/mysql5:${_MYSQL_TAG}
  waitFor:
  - pull_mysql
- id: push_mysql
  name: gcr.io/cloud-builders/docker
  args:
  - push
  - gcr.io/${PROJECT_ID}/mysql5:${_MYSQL_TAG}
  waitFor:
  - tag_mysql
- id: build_db_server
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - --file=examples/deployment/docker/db_server/Dockerfile
  - --tag=gcr.io/${PROJECT_ID}/db_server:${COMMIT_SHA}
  - --cache-from=gcr.io/${PROJECT_ID}/db_server:latest
  - .
  waitFor:
  - push_mysql
- id: build_log_server
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - --file=examples/deployment/docker/log_server/Dockerfile
  - --tag=gcr.io/${PROJECT_ID}/log_server:${COMMIT_SHA}
  - --cache-from=gcr.io/${PROJECT_ID}/log_server:latest
  - --build-arg=GO111MODULE=on
  - .
  waitFor: ["-"]
- id: build_log_signer
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - --file=examples/deployment/docker/log_signer/Dockerfile
  - --tag=gcr.io/${PROJECT_ID}/log_signer:${COMMIT_SHA}
  - --cache-from=gcr.io/${PROJECT_ID}/log_signer:latest
  - --build-arg=GO111MODULE=on
  - .
  waitFor: ["-"]
- id: build_map_server
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - --file=examples/deployment/docker/map_server/Dockerfile
  - --tag=gcr.io/${PROJECT_ID}/map_server:${COMMIT_SHA}
  - --cache-from=gcr.io/${PROJECT_ID}/map_server:latest
  - --build-arg=GO111MODULE=on
  - .
  waitFor: ["-"]
- id: push_log_server
  name: gcr.io/cloud-builders/docker
  args:
  - push
  - gcr.io/${PROJECT_ID}/log_server:${COMMIT_SHA}
  waitFor:
  - build_log_server
- id: push_log_signer
  name: gcr.io/cloud-builders/docker
  args:
  - push
  - gcr.io/${PROJECT_ID}/log_signer:${COMMIT_SHA}
  waitFor:
  - build_log_signer
- id: tag_latest_log_server
  name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - images
  - add-tag
  - gcr.io/${PROJECT_ID}/log_server:${COMMIT_SHA}
  - gcr.io/${PROJECT_ID}/log_server:latest
  waitFor:
  - push_log_server
- id: tag_latest_log_signer
  name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - images
  - add-tag
  - gcr.io/${PROJECT_ID}/log_signer:${COMMIT_SHA}
  - gcr.io/${PROJECT_ID}/log_signer:latest
  waitFor:
  - push_log_signer
- id: build_envsubst
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - examples/deployment/docker/envsubst
  - -t
  - envsubst
  waitFor: ["-"]
- id: envsubst_kubernetes_configs
  name: envsubst
  args:
  - ${_CONFIG_MAP}
  - examples/deployment/kubernetes/trillian-log-deployment.yaml
  - examples/deployment/kubernetes/trillian-log-service.yaml
  - examples/deployment/kubernetes/trillian-log-signer-deployment.yaml
  - examples/deployment/kubernetes/trillian-log-signer-service.yaml
  env:
  - PROJECT_ID=${PROJECT_ID}
  - IMAGE_TAG=${COMMIT_SHA}
  waitFor:
  - build_envsubst
- id: update_kubernetes_configs
  name: gcr.io/cloud-builders/kubectl
  args:
  - apply
  - -f=${_CONFIG_MAP}
  - -f=examples/deployment/kubernetes/trillian-log-deployment.yaml
  - -f=examples/deployment/kubernetes/trillian-log-service.yaml
  - -f=examples/deployment/kubernetes/trillian-log-signer-deployment.yaml
  - -f=examples/deployment/kubernetes/trillian-log-signer-service.yaml
  - --prune
  - --all
  - --prune-whitelist=core/v1/ConfigMap
  env:
  - CLOUDSDK_COMPUTE_ZONE=${_MASTER_ZONE}
  - CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}
  waitFor:
  - envsubst_kubernetes_configs
  - push_log_server
  - push_log_signer
images:
- gcr.io/${PROJECT_ID}/db_server:${COMMIT_SHA}
- gcr.io/${PROJECT_ID}/log_server:${COMMIT_SHA}
- gcr.io/${PROJECT_ID}/log_signer:${COMMIT_SHA}
- gcr.io/${PROJECT_ID}/map_server:${COMMIT_SHA}
