# This file contains configuration for Cloud Builds triggered by pull requests
# to this repository.

timeout: 1800s
substitutions:
  _CLUSTER_NAME: trillian-opensource-ci
  _MASTER_ZONE: us-central1-a
  _MYSQL_TAG: "8.0"
  _MYSQL_ROOT_PASSWORD: ""
  _MYSQL_PASSWORD: ""
options:
  machineType: E2_HIGHCPU_32

steps:

- id: build_db_server
  name: gcr.io/kaniko-project/executor:v1.20.0
  args:
  - --dockerfile=examples/deployment/docker/db_server/Dockerfile
  - --destination=gcr.io/${PROJECT_ID}/db_server:${COMMIT_SHA}
  - --cache=true
  - --cache-dir= # Cache is in Google Container Registry.

- id: build_log_server
  name: gcr.io/kaniko-project/executor:v1.20.0
  args:
  - --dockerfile=examples/deployment/docker/log_server/Dockerfile
  - --destination=gcr.io/${PROJECT_ID}/log_server:${COMMIT_SHA}
  - --cache=true
  - --cache-dir= # Cache is in Google Container Registry
  waitFor: ['-']
- id: build_log_signer
  name: gcr.io/kaniko-project/executor:v1.20.0
  args:
  - --dockerfile=examples/deployment/docker/log_signer/Dockerfile
  - --destination=gcr.io/${PROJECT_ID}/log_signer:${COMMIT_SHA}
  - --cache=true
  - --cache-dir= # Cache is in Google Container Registry
  waitFor: ['-']

