set -e
set -x

find . -name "*.pb.go" -exec rm {} \;
find . -name "mock_*" -exec rm {} \;
golint --set_exit_status ./...
go vet ./...
go generate -run="protoc" ./...
go generate -run="mockgen" ./...
go build ./...
go test -cover ./...
# errcheck ./...
find . -type d -exec gocyclo -over 25 {} \;
find . -exec misspell -locale US {} \;

