// Code generated by protoc-gen-go.
// source: github.com/google/trillian/trillian_api.proto
// DO NOT EDIT!

/*
Package trillian is a generated protocol buffer package.

It is generated from these files:
	github.com/google/trillian/trillian_api.proto
	github.com/google/trillian/trillian.proto

It has these top-level messages:
	TrillianApiStatus
	LeafProto
	NodeProto
	ProofProto
	QueueLeavesRequest
	QueueLeavesResponse
	GetInclusionProofRequest
	GetInclusionProofResponse
	GetInclusionProofByHashRequest
	GetInclusionProofByHashResponse
	GetConsistencyProofRequest
	GetConsistencyProofResponse
	GetLeavesByHashRequest
	GetLeavesByHashResponse
	GetLeavesByIndexRequest
	GetLeavesByIndexResponse
	GetSequencedLeafCountRequest
	GetSequencedLeafCountResponse
	GetLatestSignedLogRootRequest
	GetLatestSignedLogRootResponse
	MapLeaf
	KeyValue
	KeyValueInclusion
	GetMapLeavesRequest
	GetMapLeavesResponse
	SetMapLeavesRequest
	SetMapLeavesResponse
	GetSignedMapRootRequest
	GetSignedMapRootResponse
	DigitallySigned
	SignedEntryTimestamp
	SignedLogRoot
	SignedMapRoot
*/
package trillian

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TrillianApiStatusCode is an application level status code
type TrillianApiStatusCode int32

const (
	TrillianApiStatusCode_OK    TrillianApiStatusCode = 0
	TrillianApiStatusCode_ERROR TrillianApiStatusCode = 1
)

var TrillianApiStatusCode_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}
var TrillianApiStatusCode_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x TrillianApiStatusCode) String() string {
	return proto.EnumName(TrillianApiStatusCode_name, int32(x))
}
func (TrillianApiStatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// All operations return a TrillianApiStatus.
// TODO(Martin2112): Most of the operations are not fully defined yet. They will be implemented soon
type TrillianApiStatus struct {
	// The status code indicates the overall result of the operation.
	StatusCode TrillianApiStatusCode `protobuf:"varint,1,opt,name=status_code,json=statusCode,enum=trillian.TrillianApiStatusCode" json:"status_code,omitempty"`
	// Applications should not make assumptions about the contents of description. They
	// should use status_code only when making error handling decisions.
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *TrillianApiStatus) Reset()                    { *m = TrillianApiStatus{} }
func (m *TrillianApiStatus) String() string            { return proto.CompactTextString(m) }
func (*TrillianApiStatus) ProtoMessage()               {}
func (*TrillianApiStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LeafProto struct {
	LeafHash  []byte `protobuf:"bytes,1,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	LeafData  []byte `protobuf:"bytes,2,opt,name=leaf_data,json=leafData,proto3" json:"leaf_data,omitempty"`
	ExtraData []byte `protobuf:"bytes,3,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	LeafIndex int64  `protobuf:"varint,4,opt,name=leaf_index,json=leafIndex" json:"leaf_index,omitempty"`
}

func (m *LeafProto) Reset()                    { *m = LeafProto{} }
func (m *LeafProto) String() string            { return proto.CompactTextString(m) }
func (*LeafProto) ProtoMessage()               {}
func (*LeafProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NodeProto struct {
	NodeId       []byte `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeHash     []byte `protobuf:"bytes,2,opt,name=node_hash,json=nodeHash,proto3" json:"node_hash,omitempty"`
	NodeRevision int64  `protobuf:"varint,3,opt,name=node_revision,json=nodeRevision" json:"node_revision,omitempty"`
}

func (m *NodeProto) Reset()                    { *m = NodeProto{} }
func (m *NodeProto) String() string            { return proto.CompactTextString(m) }
func (*NodeProto) ProtoMessage()               {}
func (*NodeProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ProofProto struct {
	LeafIndex int64        `protobuf:"varint,1,opt,name=leaf_index,json=leafIndex" json:"leaf_index,omitempty"`
	ProofNode []*NodeProto `protobuf:"bytes,2,rep,name=proof_node,json=proofNode" json:"proof_node,omitempty"`
}

func (m *ProofProto) Reset()                    { *m = ProofProto{} }
func (m *ProofProto) String() string            { return proto.CompactTextString(m) }
func (*ProofProto) ProtoMessage()               {}
func (*ProofProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProofProto) GetProofNode() []*NodeProto {
	if m != nil {
		return m.ProofNode
	}
	return nil
}

type QueueLeavesRequest struct {
	LogId  int64        `protobuf:"varint,1,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	Leaves []*LeafProto `protobuf:"bytes,2,rep,name=leaves" json:"leaves,omitempty"`
}

func (m *QueueLeavesRequest) Reset()                    { *m = QueueLeavesRequest{} }
func (m *QueueLeavesRequest) String() string            { return proto.CompactTextString(m) }
func (*QueueLeavesRequest) ProtoMessage()               {}
func (*QueueLeavesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QueueLeavesRequest) GetLeaves() []*LeafProto {
	if m != nil {
		return m.Leaves
	}
	return nil
}

// TODO(Martin2112): This will eventually contain the signed timestamps and stuff that we return for
// the queued leaves
type QueueLeavesResponse struct {
	Status *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *QueueLeavesResponse) Reset()                    { *m = QueueLeavesResponse{} }
func (m *QueueLeavesResponse) String() string            { return proto.CompactTextString(m) }
func (*QueueLeavesResponse) ProtoMessage()               {}
func (*QueueLeavesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *QueueLeavesResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetInclusionProofRequest struct {
	LogId     int64 `protobuf:"varint,1,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	LeafIndex int64 `protobuf:"varint,2,opt,name=leaf_index,json=leafIndex" json:"leaf_index,omitempty"`
}

func (m *GetInclusionProofRequest) Reset()                    { *m = GetInclusionProofRequest{} }
func (m *GetInclusionProofRequest) String() string            { return proto.CompactTextString(m) }
func (*GetInclusionProofRequest) ProtoMessage()               {}
func (*GetInclusionProofRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type GetInclusionProofResponse struct {
	Status *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Proof  *ProofProto        `protobuf:"bytes,2,opt,name=proof" json:"proof,omitempty"`
}

func (m *GetInclusionProofResponse) Reset()                    { *m = GetInclusionProofResponse{} }
func (m *GetInclusionProofResponse) String() string            { return proto.CompactTextString(m) }
func (*GetInclusionProofResponse) ProtoMessage()               {}
func (*GetInclusionProofResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetInclusionProofResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetInclusionProofResponse) GetProof() *ProofProto {
	if m != nil {
		return m.Proof
	}
	return nil
}

type GetInclusionProofByHashRequest struct {
	LogId    int64  `protobuf:"varint,1,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	LeafHash []byte `protobuf:"bytes,2,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	TreeSize int64  `protobuf:"varint,3,opt,name=tree_size,json=treeSize" json:"tree_size,omitempty"`
}

func (m *GetInclusionProofByHashRequest) Reset()                    { *m = GetInclusionProofByHashRequest{} }
func (m *GetInclusionProofByHashRequest) String() string            { return proto.CompactTextString(m) }
func (*GetInclusionProofByHashRequest) ProtoMessage()               {}
func (*GetInclusionProofByHashRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type GetInclusionProofByHashResponse struct {
	Status *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	// Logs can potentially contain leaves with duplicate hashes so it's possible
	// for this to return multiple proofs.
	Proof []*ProofProto `protobuf:"bytes,2,rep,name=proof" json:"proof,omitempty"`
}

func (m *GetInclusionProofByHashResponse) Reset()                    { *m = GetInclusionProofByHashResponse{} }
func (m *GetInclusionProofByHashResponse) String() string            { return proto.CompactTextString(m) }
func (*GetInclusionProofByHashResponse) ProtoMessage()               {}
func (*GetInclusionProofByHashResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetInclusionProofByHashResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetInclusionProofByHashResponse) GetProof() []*ProofProto {
	if m != nil {
		return m.Proof
	}
	return nil
}

type GetConsistencyProofRequest struct {
	LogId int64 `protobuf:"varint,1,opt,name=log_id,json=logId" json:"log_id,omitempty"`
}

func (m *GetConsistencyProofRequest) Reset()                    { *m = GetConsistencyProofRequest{} }
func (m *GetConsistencyProofRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConsistencyProofRequest) ProtoMessage()               {}
func (*GetConsistencyProofRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type GetConsistencyProofResponse struct {
	Status *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *GetConsistencyProofResponse) Reset()                    { *m = GetConsistencyProofResponse{} }
func (m *GetConsistencyProofResponse) String() string            { return proto.CompactTextString(m) }
func (*GetConsistencyProofResponse) ProtoMessage()               {}
func (*GetConsistencyProofResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetConsistencyProofResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetLeavesByHashRequest struct {
	LogId    int64    `protobuf:"varint,1,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	LeafHash [][]byte `protobuf:"bytes,2,rep,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
}

func (m *GetLeavesByHashRequest) Reset()                    { *m = GetLeavesByHashRequest{} }
func (m *GetLeavesByHashRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLeavesByHashRequest) ProtoMessage()               {}
func (*GetLeavesByHashRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type GetLeavesByHashResponse struct {
	Status *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Leaves []*LeafProto       `protobuf:"bytes,2,rep,name=leaves" json:"leaves,omitempty"`
}

func (m *GetLeavesByHashResponse) Reset()                    { *m = GetLeavesByHashResponse{} }
func (m *GetLeavesByHashResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLeavesByHashResponse) ProtoMessage()               {}
func (*GetLeavesByHashResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetLeavesByHashResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetLeavesByHashResponse) GetLeaves() []*LeafProto {
	if m != nil {
		return m.Leaves
	}
	return nil
}

type GetLeavesByIndexRequest struct {
	LogId     int64   `protobuf:"varint,1,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	LeafIndex []int64 `protobuf:"varint,2,rep,packed,name=leaf_index,json=leafIndex" json:"leaf_index,omitempty"`
}

func (m *GetLeavesByIndexRequest) Reset()                    { *m = GetLeavesByIndexRequest{} }
func (m *GetLeavesByIndexRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLeavesByIndexRequest) ProtoMessage()               {}
func (*GetLeavesByIndexRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type GetLeavesByIndexResponse struct {
	Status *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Leaves []*LeafProto       `protobuf:"bytes,2,rep,name=leaves" json:"leaves,omitempty"`
}

func (m *GetLeavesByIndexResponse) Reset()                    { *m = GetLeavesByIndexResponse{} }
func (m *GetLeavesByIndexResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLeavesByIndexResponse) ProtoMessage()               {}
func (*GetLeavesByIndexResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetLeavesByIndexResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetLeavesByIndexResponse) GetLeaves() []*LeafProto {
	if m != nil {
		return m.Leaves
	}
	return nil
}

type GetSequencedLeafCountRequest struct {
	LogId int64 `protobuf:"varint,1,opt,name=log_id,json=logId" json:"log_id,omitempty"`
}

func (m *GetSequencedLeafCountRequest) Reset()                    { *m = GetSequencedLeafCountRequest{} }
func (m *GetSequencedLeafCountRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSequencedLeafCountRequest) ProtoMessage()               {}
func (*GetSequencedLeafCountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type GetSequencedLeafCountResponse struct {
	Status *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *GetSequencedLeafCountResponse) Reset()                    { *m = GetSequencedLeafCountResponse{} }
func (m *GetSequencedLeafCountResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSequencedLeafCountResponse) ProtoMessage()               {}
func (*GetSequencedLeafCountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetSequencedLeafCountResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetLatestSignedLogRootRequest struct {
	LogId int64 `protobuf:"varint,1,opt,name=log_id,json=logId" json:"log_id,omitempty"`
}

func (m *GetLatestSignedLogRootRequest) Reset()                    { *m = GetLatestSignedLogRootRequest{} }
func (m *GetLatestSignedLogRootRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLatestSignedLogRootRequest) ProtoMessage()               {}
func (*GetLatestSignedLogRootRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type GetLatestSignedLogRootResponse struct {
	Status        *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	SignedLogRoot *SignedLogRoot     `protobuf:"bytes,2,opt,name=signed_log_root,json=signedLogRoot" json:"signed_log_root,omitempty"`
}

func (m *GetLatestSignedLogRootResponse) Reset()                    { *m = GetLatestSignedLogRootResponse{} }
func (m *GetLatestSignedLogRootResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLatestSignedLogRootResponse) ProtoMessage()               {}
func (*GetLatestSignedLogRootResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *GetLatestSignedLogRootResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetLatestSignedLogRootResponse) GetSignedLogRoot() *SignedLogRoot {
	if m != nil {
		return m.SignedLogRoot
	}
	return nil
}

// MapLeaf represents the data behind Map leaves.
type MapLeaf struct {
	// leaf_hash is the tree hash of leaf_value.
	LeafHash []byte `protobuf:"bytes,1,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	// leaf_value is the data the tree commits to.
	LeafValue []byte `protobuf:"bytes,2,opt,name=leaf_value,json=leafValue,proto3" json:"leaf_value,omitempty"`
	// extra_data holds related contextual data, but is not covered by any hash.
	ExtraData []byte `protobuf:"bytes,3,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
}

func (m *MapLeaf) Reset()                    { *m = MapLeaf{} }
func (m *MapLeaf) String() string            { return proto.CompactTextString(m) }
func (*MapLeaf) ProtoMessage()               {}
func (*MapLeaf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type KeyValue struct {
	Key   []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *MapLeaf `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *KeyValue) GetValue() *MapLeaf {
	if m != nil {
		return m.Value
	}
	return nil
}

type KeyValueInclusion struct {
	KeyValue  *KeyValue `protobuf:"bytes,1,opt,name=key_value,json=keyValue" json:"key_value,omitempty"`
	Inclusion [][]byte  `protobuf:"bytes,2,rep,name=inclusion,proto3" json:"inclusion,omitempty"`
}

func (m *KeyValueInclusion) Reset()                    { *m = KeyValueInclusion{} }
func (m *KeyValueInclusion) String() string            { return proto.CompactTextString(m) }
func (*KeyValueInclusion) ProtoMessage()               {}
func (*KeyValueInclusion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *KeyValueInclusion) GetKeyValue() *KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

type GetMapLeavesRequest struct {
	MapId int64    `protobuf:"varint,1,opt,name=map_id,json=mapId" json:"map_id,omitempty"`
	Key   [][]byte `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
}

func (m *GetMapLeavesRequest) Reset()                    { *m = GetMapLeavesRequest{} }
func (m *GetMapLeavesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMapLeavesRequest) ProtoMessage()               {}
func (*GetMapLeavesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type GetMapLeavesResponse struct {
	Status   *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	KeyValue []*KeyValue        `protobuf:"bytes,2,rep,name=key_value,json=keyValue" json:"key_value,omitempty"`
	MapRoot  *SignedMapRoot     `protobuf:"bytes,3,opt,name=map_root,json=mapRoot" json:"map_root,omitempty"`
}

func (m *GetMapLeavesResponse) Reset()                    { *m = GetMapLeavesResponse{} }
func (m *GetMapLeavesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMapLeavesResponse) ProtoMessage()               {}
func (*GetMapLeavesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *GetMapLeavesResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetMapLeavesResponse) GetKeyValue() []*KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

func (m *GetMapLeavesResponse) GetMapRoot() *SignedMapRoot {
	if m != nil {
		return m.MapRoot
	}
	return nil
}

type SetMapLeavesRequest struct {
	MapId             int64          `protobuf:"varint,1,opt,name=map_id,json=mapId" json:"map_id,omitempty"`
	KeyValue          []*KeyValue    `protobuf:"bytes,2,rep,name=key_value,json=keyValue" json:"key_value,omitempty"`
	IncludesEntriesTo *SignedLogRoot `protobuf:"bytes,3,opt,name=includes_entries_to,json=includesEntriesTo" json:"includes_entries_to,omitempty"`
}

func (m *SetMapLeavesRequest) Reset()                    { *m = SetMapLeavesRequest{} }
func (m *SetMapLeavesRequest) String() string            { return proto.CompactTextString(m) }
func (*SetMapLeavesRequest) ProtoMessage()               {}
func (*SetMapLeavesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *SetMapLeavesRequest) GetKeyValue() []*KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

func (m *SetMapLeavesRequest) GetIncludesEntriesTo() *SignedLogRoot {
	if m != nil {
		return m.IncludesEntriesTo
	}
	return nil
}

type SetMapLeavesResponse struct {
	Status *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *SetMapLeavesResponse) Reset()                    { *m = SetMapLeavesResponse{} }
func (m *SetMapLeavesResponse) String() string            { return proto.CompactTextString(m) }
func (*SetMapLeavesResponse) ProtoMessage()               {}
func (*SetMapLeavesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *SetMapLeavesResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetSignedMapRootRequest struct {
	MapId int64 `protobuf:"varint,1,opt,name=map_id,json=mapId" json:"map_id,omitempty"`
}

func (m *GetSignedMapRootRequest) Reset()                    { *m = GetSignedMapRootRequest{} }
func (m *GetSignedMapRootRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSignedMapRootRequest) ProtoMessage()               {}
func (*GetSignedMapRootRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type GetSignedMapRootResponse struct {
	Status  *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	MapRoot *SignedMapRoot     `protobuf:"bytes,2,opt,name=map_root,json=mapRoot" json:"map_root,omitempty"`
}

func (m *GetSignedMapRootResponse) Reset()                    { *m = GetSignedMapRootResponse{} }
func (m *GetSignedMapRootResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSignedMapRootResponse) ProtoMessage()               {}
func (*GetSignedMapRootResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *GetSignedMapRootResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetSignedMapRootResponse) GetMapRoot() *SignedMapRoot {
	if m != nil {
		return m.MapRoot
	}
	return nil
}

func init() {
	proto.RegisterType((*TrillianApiStatus)(nil), "trillian.TrillianApiStatus")
	proto.RegisterType((*LeafProto)(nil), "trillian.LeafProto")
	proto.RegisterType((*NodeProto)(nil), "trillian.NodeProto")
	proto.RegisterType((*ProofProto)(nil), "trillian.ProofProto")
	proto.RegisterType((*QueueLeavesRequest)(nil), "trillian.QueueLeavesRequest")
	proto.RegisterType((*QueueLeavesResponse)(nil), "trillian.QueueLeavesResponse")
	proto.RegisterType((*GetInclusionProofRequest)(nil), "trillian.GetInclusionProofRequest")
	proto.RegisterType((*GetInclusionProofResponse)(nil), "trillian.GetInclusionProofResponse")
	proto.RegisterType((*GetInclusionProofByHashRequest)(nil), "trillian.GetInclusionProofByHashRequest")
	proto.RegisterType((*GetInclusionProofByHashResponse)(nil), "trillian.GetInclusionProofByHashResponse")
	proto.RegisterType((*GetConsistencyProofRequest)(nil), "trillian.GetConsistencyProofRequest")
	proto.RegisterType((*GetConsistencyProofResponse)(nil), "trillian.GetConsistencyProofResponse")
	proto.RegisterType((*GetLeavesByHashRequest)(nil), "trillian.GetLeavesByHashRequest")
	proto.RegisterType((*GetLeavesByHashResponse)(nil), "trillian.GetLeavesByHashResponse")
	proto.RegisterType((*GetLeavesByIndexRequest)(nil), "trillian.GetLeavesByIndexRequest")
	proto.RegisterType((*GetLeavesByIndexResponse)(nil), "trillian.GetLeavesByIndexResponse")
	proto.RegisterType((*GetSequencedLeafCountRequest)(nil), "trillian.GetSequencedLeafCountRequest")
	proto.RegisterType((*GetSequencedLeafCountResponse)(nil), "trillian.GetSequencedLeafCountResponse")
	proto.RegisterType((*GetLatestSignedLogRootRequest)(nil), "trillian.GetLatestSignedLogRootRequest")
	proto.RegisterType((*GetLatestSignedLogRootResponse)(nil), "trillian.GetLatestSignedLogRootResponse")
	proto.RegisterType((*MapLeaf)(nil), "trillian.MapLeaf")
	proto.RegisterType((*KeyValue)(nil), "trillian.KeyValue")
	proto.RegisterType((*KeyValueInclusion)(nil), "trillian.KeyValueInclusion")
	proto.RegisterType((*GetMapLeavesRequest)(nil), "trillian.GetMapLeavesRequest")
	proto.RegisterType((*GetMapLeavesResponse)(nil), "trillian.GetMapLeavesResponse")
	proto.RegisterType((*SetMapLeavesRequest)(nil), "trillian.SetMapLeavesRequest")
	proto.RegisterType((*SetMapLeavesResponse)(nil), "trillian.SetMapLeavesResponse")
	proto.RegisterType((*GetSignedMapRootRequest)(nil), "trillian.GetSignedMapRootRequest")
	proto.RegisterType((*GetSignedMapRootResponse)(nil), "trillian.GetSignedMapRootResponse")
	proto.RegisterEnum("trillian.TrillianApiStatusCode", TrillianApiStatusCode_name, TrillianApiStatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for TrillianLog service

type TrillianLogClient interface {
	// Corresponds to the LeafQueuer API
	QueueLeaves(ctx context.Context, in *QueueLeavesRequest, opts ...grpc.CallOption) (*QueueLeavesResponse, error)
	// No direct equivalent at the storage level
	GetInclusionProof(ctx context.Context, in *GetInclusionProofRequest, opts ...grpc.CallOption) (*GetInclusionProofResponse, error)
	GetInclusionProofByHash(ctx context.Context, in *GetInclusionProofByHashRequest, opts ...grpc.CallOption) (*GetInclusionProofByHashResponse, error)
	GetConsistencyProof(ctx context.Context, in *GetConsistencyProofRequest, opts ...grpc.CallOption) (*GetConsistencyProofResponse, error)
	// Corresponds to the LogRootReader API
	GetLatestSignedLogRoot(ctx context.Context, in *GetLatestSignedLogRootRequest, opts ...grpc.CallOption) (*GetLatestSignedLogRootResponse, error)
	// Corresponds to the LeafReader API
	GetSequencedLeafCount(ctx context.Context, in *GetSequencedLeafCountRequest, opts ...grpc.CallOption) (*GetSequencedLeafCountResponse, error)
	GetLeavesByIndex(ctx context.Context, in *GetLeavesByIndexRequest, opts ...grpc.CallOption) (*GetLeavesByIndexResponse, error)
	GetLeavesByHash(ctx context.Context, in *GetLeavesByHashRequest, opts ...grpc.CallOption) (*GetLeavesByHashResponse, error)
}

type trillianLogClient struct {
	cc *grpc.ClientConn
}

func NewTrillianLogClient(cc *grpc.ClientConn) TrillianLogClient {
	return &trillianLogClient{cc}
}

func (c *trillianLogClient) QueueLeaves(ctx context.Context, in *QueueLeavesRequest, opts ...grpc.CallOption) (*QueueLeavesResponse, error) {
	out := new(QueueLeavesResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/QueueLeaves", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianLogClient) GetInclusionProof(ctx context.Context, in *GetInclusionProofRequest, opts ...grpc.CallOption) (*GetInclusionProofResponse, error) {
	out := new(GetInclusionProofResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/GetInclusionProof", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianLogClient) GetInclusionProofByHash(ctx context.Context, in *GetInclusionProofByHashRequest, opts ...grpc.CallOption) (*GetInclusionProofByHashResponse, error) {
	out := new(GetInclusionProofByHashResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/GetInclusionProofByHash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianLogClient) GetConsistencyProof(ctx context.Context, in *GetConsistencyProofRequest, opts ...grpc.CallOption) (*GetConsistencyProofResponse, error) {
	out := new(GetConsistencyProofResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/GetConsistencyProof", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianLogClient) GetLatestSignedLogRoot(ctx context.Context, in *GetLatestSignedLogRootRequest, opts ...grpc.CallOption) (*GetLatestSignedLogRootResponse, error) {
	out := new(GetLatestSignedLogRootResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/GetLatestSignedLogRoot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianLogClient) GetSequencedLeafCount(ctx context.Context, in *GetSequencedLeafCountRequest, opts ...grpc.CallOption) (*GetSequencedLeafCountResponse, error) {
	out := new(GetSequencedLeafCountResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/GetSequencedLeafCount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianLogClient) GetLeavesByIndex(ctx context.Context, in *GetLeavesByIndexRequest, opts ...grpc.CallOption) (*GetLeavesByIndexResponse, error) {
	out := new(GetLeavesByIndexResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/GetLeavesByIndex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianLogClient) GetLeavesByHash(ctx context.Context, in *GetLeavesByHashRequest, opts ...grpc.CallOption) (*GetLeavesByHashResponse, error) {
	out := new(GetLeavesByHashResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/GetLeavesByHash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TrillianLog service

type TrillianLogServer interface {
	// Corresponds to the LeafQueuer API
	QueueLeaves(context.Context, *QueueLeavesRequest) (*QueueLeavesResponse, error)
	// No direct equivalent at the storage level
	GetInclusionProof(context.Context, *GetInclusionProofRequest) (*GetInclusionProofResponse, error)
	GetInclusionProofByHash(context.Context, *GetInclusionProofByHashRequest) (*GetInclusionProofByHashResponse, error)
	GetConsistencyProof(context.Context, *GetConsistencyProofRequest) (*GetConsistencyProofResponse, error)
	// Corresponds to the LogRootReader API
	GetLatestSignedLogRoot(context.Context, *GetLatestSignedLogRootRequest) (*GetLatestSignedLogRootResponse, error)
	// Corresponds to the LeafReader API
	GetSequencedLeafCount(context.Context, *GetSequencedLeafCountRequest) (*GetSequencedLeafCountResponse, error)
	GetLeavesByIndex(context.Context, *GetLeavesByIndexRequest) (*GetLeavesByIndexResponse, error)
	GetLeavesByHash(context.Context, *GetLeavesByHashRequest) (*GetLeavesByHashResponse, error)
}

func RegisterTrillianLogServer(s *grpc.Server, srv TrillianLogServer) {
	s.RegisterService(&_TrillianLog_serviceDesc, srv)
}

func _TrillianLog_QueueLeaves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueLeavesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).QueueLeaves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/QueueLeaves",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).QueueLeaves(ctx, req.(*QueueLeavesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianLog_GetInclusionProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInclusionProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).GetInclusionProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/GetInclusionProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).GetInclusionProof(ctx, req.(*GetInclusionProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianLog_GetInclusionProofByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInclusionProofByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).GetInclusionProofByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/GetInclusionProofByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).GetInclusionProofByHash(ctx, req.(*GetInclusionProofByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianLog_GetConsistencyProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsistencyProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).GetConsistencyProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/GetConsistencyProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).GetConsistencyProof(ctx, req.(*GetConsistencyProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianLog_GetLatestSignedLogRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestSignedLogRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).GetLatestSignedLogRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/GetLatestSignedLogRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).GetLatestSignedLogRoot(ctx, req.(*GetLatestSignedLogRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianLog_GetSequencedLeafCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSequencedLeafCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).GetSequencedLeafCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/GetSequencedLeafCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).GetSequencedLeafCount(ctx, req.(*GetSequencedLeafCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianLog_GetLeavesByIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeavesByIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).GetLeavesByIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/GetLeavesByIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).GetLeavesByIndex(ctx, req.(*GetLeavesByIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianLog_GetLeavesByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeavesByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).GetLeavesByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/GetLeavesByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).GetLeavesByHash(ctx, req.(*GetLeavesByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrillianLog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trillian.TrillianLog",
	HandlerType: (*TrillianLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueueLeaves",
			Handler:    _TrillianLog_QueueLeaves_Handler,
		},
		{
			MethodName: "GetInclusionProof",
			Handler:    _TrillianLog_GetInclusionProof_Handler,
		},
		{
			MethodName: "GetInclusionProofByHash",
			Handler:    _TrillianLog_GetInclusionProofByHash_Handler,
		},
		{
			MethodName: "GetConsistencyProof",
			Handler:    _TrillianLog_GetConsistencyProof_Handler,
		},
		{
			MethodName: "GetLatestSignedLogRoot",
			Handler:    _TrillianLog_GetLatestSignedLogRoot_Handler,
		},
		{
			MethodName: "GetSequencedLeafCount",
			Handler:    _TrillianLog_GetSequencedLeafCount_Handler,
		},
		{
			MethodName: "GetLeavesByIndex",
			Handler:    _TrillianLog_GetLeavesByIndex_Handler,
		},
		{
			MethodName: "GetLeavesByHash",
			Handler:    _TrillianLog_GetLeavesByHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for TrillianMap service

type TrillianMapClient interface {
	GetLeaves(ctx context.Context, in *GetMapLeavesRequest, opts ...grpc.CallOption) (*GetMapLeavesResponse, error)
	SetLeaves(ctx context.Context, in *SetMapLeavesRequest, opts ...grpc.CallOption) (*SetMapLeavesResponse, error)
	GetSignedMapRoot(ctx context.Context, in *GetSignedMapRootRequest, opts ...grpc.CallOption) (*GetSignedMapRootResponse, error)
}

type trillianMapClient struct {
	cc *grpc.ClientConn
}

func NewTrillianMapClient(cc *grpc.ClientConn) TrillianMapClient {
	return &trillianMapClient{cc}
}

func (c *trillianMapClient) GetLeaves(ctx context.Context, in *GetMapLeavesRequest, opts ...grpc.CallOption) (*GetMapLeavesResponse, error) {
	out := new(GetMapLeavesResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianMap/GetLeaves", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianMapClient) SetLeaves(ctx context.Context, in *SetMapLeavesRequest, opts ...grpc.CallOption) (*SetMapLeavesResponse, error) {
	out := new(SetMapLeavesResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianMap/SetLeaves", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianMapClient) GetSignedMapRoot(ctx context.Context, in *GetSignedMapRootRequest, opts ...grpc.CallOption) (*GetSignedMapRootResponse, error) {
	out := new(GetSignedMapRootResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianMap/GetSignedMapRoot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TrillianMap service

type TrillianMapServer interface {
	GetLeaves(context.Context, *GetMapLeavesRequest) (*GetMapLeavesResponse, error)
	SetLeaves(context.Context, *SetMapLeavesRequest) (*SetMapLeavesResponse, error)
	GetSignedMapRoot(context.Context, *GetSignedMapRootRequest) (*GetSignedMapRootResponse, error)
}

func RegisterTrillianMapServer(s *grpc.Server, srv TrillianMapServer) {
	s.RegisterService(&_TrillianMap_serviceDesc, srv)
}

func _TrillianMap_GetLeaves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMapLeavesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianMapServer).GetLeaves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianMap/GetLeaves",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianMapServer).GetLeaves(ctx, req.(*GetMapLeavesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianMap_SetLeaves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMapLeavesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianMapServer).SetLeaves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianMap/SetLeaves",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianMapServer).SetLeaves(ctx, req.(*SetMapLeavesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianMap_GetSignedMapRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignedMapRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianMapServer).GetSignedMapRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianMap/GetSignedMapRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianMapServer).GetSignedMapRoot(ctx, req.(*GetSignedMapRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrillianMap_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trillian.TrillianMap",
	HandlerType: (*TrillianMapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLeaves",
			Handler:    _TrillianMap_GetLeaves_Handler,
		},
		{
			MethodName: "SetLeaves",
			Handler:    _TrillianMap_SetLeaves_Handler,
		},
		{
			MethodName: "GetSignedMapRoot",
			Handler:    _TrillianMap_GetSignedMapRoot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("github.com/google/trillian/trillian_api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x57, 0x5b, 0x6f, 0xe3, 0xc4,
	0x17, 0xaf, 0xe3, 0x7f, 0xd3, 0xf8, 0x64, 0xf7, 0xbf, 0xed, 0xb4, 0xa5, 0x59, 0xb7, 0xdd, 0xcd,
	0xce, 0x02, 0xcd, 0x16, 0x91, 0xa2, 0x54, 0xf0, 0xc8, 0xa5, 0xa5, 0x0a, 0xa1, 0x29, 0x2d, 0x4e,
	0x85, 0x56, 0x42, 0xc2, 0x9a, 0xc6, 0xd3, 0xd4, 0x34, 0xf1, 0x78, 0xe3, 0x49, 0xd9, 0x2c, 0x3c,
	0x81, 0xc4, 0x47, 0xe0, 0x1b, 0xc0, 0x33, 0x1f, 0x11, 0xcd, 0xf8, 0x16, 0xc7, 0xce, 0xa5, 0x64,
	0xc5, 0x9b, 0x73, 0x2e, 0xbf, 0xf3, 0x3b, 0x97, 0x99, 0x39, 0x81, 0x0f, 0x3b, 0x36, 0xbf, 0x19,
	0x5c, 0x55, 0xdb, 0xac, 0x77, 0xd0, 0x61, 0xac, 0xd3, 0xa5, 0x07, 0xbc, 0x6f, 0x77, 0xbb, 0x36,
	0x71, 0xa2, 0x0f, 0x93, 0xb8, 0x76, 0xd5, 0xed, 0x33, 0xce, 0x50, 0x21, 0x94, 0xe9, 0x2f, 0xe6,
	0x70, 0xf4, 0x9d, 0xf0, 0x4f, 0xb0, 0x76, 0x19, 0x48, 0xbe, 0x70, 0xed, 0x16, 0x27, 0x7c, 0xe0,
	0xa1, 0xcf, 0xa1, 0xe8, 0xc9, 0x2f, 0xb3, 0xcd, 0x2c, 0x5a, 0x52, 0xca, 0x4a, 0xe5, 0xff, 0xb5,
	0xa7, 0xd5, 0xc8, 0x35, 0xe5, 0x71, 0xcc, 0x2c, 0x6a, 0x80, 0x17, 0x7d, 0xa3, 0x32, 0x14, 0x2d,
	0xea, 0xb5, 0xfb, 0xb6, 0xcb, 0x6d, 0xe6, 0x94, 0x72, 0x65, 0xa5, 0xa2, 0x19, 0xa3, 0x22, 0xfc,
	0x9b, 0x02, 0x5a, 0x93, 0x92, 0xeb, 0x0b, 0xc9, 0x7d, 0x1b, 0xb4, 0x2e, 0x25, 0xd7, 0xe6, 0x0d,
	0xf1, 0x6e, 0x64, 0xbc, 0x07, 0x46, 0x41, 0x08, 0xbe, 0x22, 0xde, 0x4d, 0xa4, 0xb4, 0x08, 0x27,
	0x12, 0x2a, 0x50, 0x7e, 0x49, 0x38, 0x41, 0xbb, 0x00, 0xf4, 0x35, 0xef, 0x13, 0x5f, 0xab, 0x4a,
	0xad, 0x26, 0x25, 0xa1, 0x5a, 0xfa, 0xda, 0x8e, 0x45, 0x5f, 0x97, 0xfe, 0x57, 0x56, 0x2a, 0xaa,
	0x21, 0xd1, 0x1a, 0x42, 0x80, 0xaf, 0x41, 0xfb, 0x86, 0x59, 0xd4, 0x27, 0xb1, 0x05, 0x2b, 0x0e,
	0xb3, 0xa8, 0x69, 0x5b, 0x01, 0x85, 0xbc, 0xf8, 0xd9, 0xb0, 0x04, 0x01, 0xa9, 0x90, 0xec, 0x02,
	0x02, 0x42, 0x20, 0xd9, 0x3d, 0x87, 0x87, 0x52, 0xd9, 0xa7, 0x77, 0xb6, 0x27, 0x92, 0x55, 0x65,
	0x90, 0x07, 0x42, 0x68, 0x04, 0x32, 0x6c, 0x02, 0x5c, 0xf4, 0x19, 0x0b, 0xb2, 0x4d, 0x92, 0x52,
	0xc6, 0x48, 0xa1, 0x1a, 0x80, 0x2b, 0x8c, 0x4d, 0x01, 0x51, 0xca, 0x95, 0xd5, 0x4a, 0xb1, 0xb6,
	0x1e, 0x57, 0x3f, 0x22, 0x6c, 0x68, 0xd2, 0x4c, 0xfc, 0xc6, 0x2f, 0x01, 0x7d, 0x3b, 0xa0, 0x03,
	0xda, 0xa4, 0xe4, 0x8e, 0x7a, 0x06, 0x7d, 0x35, 0xa0, 0x1e, 0x47, 0x9b, 0x90, 0xef, 0xb2, 0x4e,
	0x98, 0x90, 0x6a, 0x2c, 0x77, 0x59, 0xa7, 0x61, 0xa1, 0x0f, 0x20, 0xdf, 0x95, 0x76, 0x69, 0xf0,
	0xa8, 0x25, 0x46, 0x60, 0x82, 0xbf, 0x86, 0xf5, 0x04, 0xb2, 0xe7, 0x32, 0xc7, 0xa3, 0xe8, 0x10,
	0xf2, 0x7e, 0xbf, 0x25, 0x74, 0xb1, 0xb6, 0x3d, 0x65, 0x3c, 0x8c, 0xc0, 0x14, 0x5f, 0x40, 0xa9,
	0x4e, 0x79, 0xc3, 0x69, 0x77, 0x07, 0xa2, 0x2c, 0xb2, 0x24, 0x33, 0xb8, 0x26, 0x6b, 0x95, 0x1b,
	0x6f, 0xe0, 0x2f, 0xf0, 0x38, 0x03, 0x71, 0x01, 0x8e, 0x68, 0x1f, 0x96, 0x65, 0x59, 0x65, 0xac,
	0x62, 0x6d, 0x23, 0xf6, 0x89, 0x3b, 0x68, 0xf8, 0x26, 0xf8, 0x15, 0x3c, 0x49, 0x45, 0x3f, 0x1a,
	0x8a, 0xb1, 0x98, 0x91, 0x55, 0x62, 0xde, 0x73, 0xe9, 0x79, 0xe7, 0x7d, 0x4a, 0x4d, 0xcf, 0x7e,
	0x43, 0x83, 0x69, 0x2a, 0x08, 0x41, 0xcb, 0x7e, 0x43, 0xf1, 0xaf, 0x0a, 0x3c, 0x9d, 0x18, 0xf3,
	0x2d, 0xe5, 0xad, 0xce, 0xca, 0xfb, 0x10, 0xf4, 0x3a, 0xe5, 0xc7, 0xcc, 0xf1, 0x6c, 0x8f, 0x53,
	0xa7, 0x3d, 0x9c, 0xa3, 0x93, 0xd8, 0x80, 0xed, 0x4c, 0xa7, 0x45, 0x06, 0xaa, 0x09, 0xef, 0xd4,
	0x29, 0xf7, 0x47, 0xf3, 0xdf, 0x14, 0x5e, 0x1d, 0x2d, 0x3c, 0xfe, 0x19, 0xb6, 0x52, 0x68, 0x8b,
	0x94, 0xf4, 0x5e, 0xe7, 0xec, 0x3c, 0x11, 0x5c, 0x4e, 0xf7, 0x3d, 0x8f, 0x86, 0x3a, 0x7e, 0x34,
	0x4a, 0x69, 0xc0, 0xff, 0x2c, 0x9d, 0x8f, 0x61, 0xa7, 0x4e, 0x79, 0x4b, 0x64, 0xe0, 0xb4, 0xa9,
	0x25, 0x0c, 0x8e, 0xd9, 0xc0, 0xe1, 0x33, 0x86, 0xe4, 0x12, 0x76, 0x27, 0xb8, 0x2d, 0x32, 0x26,
	0x9f, 0x48, 0xd4, 0x26, 0xe1, 0xd4, 0xe3, 0x2d, 0xbb, 0xe3, 0x50, 0xab, 0xc9, 0x3a, 0x06, 0x63,
	0xb3, 0xd8, 0xfc, 0xa1, 0xc8, 0x03, 0x9e, 0xe9, 0xb8, 0x48, 0x25, 0x3f, 0x83, 0x47, 0x9e, 0x44,
	0x33, 0x45, 0xd4, 0x3e, 0x63, 0x3c, 0xb8, 0x6d, 0xb6, 0x62, 0xef, 0x64, 0xb8, 0x87, 0xde, 0xe8,
	0x4f, 0x6c, 0xc1, 0xca, 0x19, 0x71, 0x45, 0x75, 0xa6, 0x3f, 0x9d, 0xe1, 0x88, 0xdc, 0x91, 0xee,
	0x80, 0x06, 0x17, 0x8d, 0x34, 0xff, 0x4e, 0x08, 0x66, 0x3c, 0x9e, 0xf8, 0x04, 0x0a, 0xa7, 0x74,
	0xe8, 0x9b, 0xae, 0x82, 0x7a, 0x4b, 0x87, 0x41, 0x00, 0xf1, 0x89, 0xf6, 0x60, 0x39, 0x86, 0x2d,
	0xd6, 0xd6, 0x62, 0xea, 0x01, 0x35, 0xc3, 0xd7, 0xe3, 0x2b, 0x58, 0x0b, 0x61, 0xa2, 0x6b, 0x0b,
	0x1d, 0x80, 0x76, 0x4b, 0x87, 0x01, 0x31, 0xbf, 0x74, 0x28, 0x46, 0x08, 0xed, 0x8d, 0xc2, 0x6d,
	0x48, 0x60, 0x07, 0x34, 0x3b, 0xf4, 0x0e, 0x4e, 0x6e, 0x2c, 0xc0, 0x9f, 0xc2, 0x7a, 0x9d, 0x72,
	0x3f, 0x70, 0xf2, 0x01, 0xec, 0x11, 0x77, 0xa4, 0xaf, 0x3d, 0xe2, 0x36, 0xac, 0x30, 0x19, 0x1f,
	0x45, 0x7c, 0xe2, 0xbf, 0x15, 0xd8, 0x48, 0x02, 0x2c, 0xd2, 0xdf, 0x44, 0x72, 0xfe, 0x61, 0x99,
	0x9e, 0x5c, 0x0d, 0x0a, 0x82, 0xa7, 0x9c, 0x04, 0x35, 0x7b, 0x12, 0xce, 0x88, 0x2b, 0x27, 0x61,
	0xa5, 0xe7, 0x7f, 0xe0, 0xbf, 0x14, 0x58, 0x6f, 0xcd, 0x9f, 0xf3, 0xbd, 0x39, 0xd5, 0x61, 0x5d,
	0xd6, 0xd7, 0xa2, 0x9e, 0x49, 0x1d, 0xde, 0xb7, 0xa9, 0x67, 0x72, 0x36, 0x89, 0x5e, 0x38, 0xa8,
	0x6b, 0xa1, 0xcf, 0x89, 0xef, 0x72, 0xc9, 0xf0, 0x29, 0x6c, 0xb4, 0xde, 0x56, 0x69, 0xf1, 0x47,
	0xf2, 0x9a, 0x4c, 0x96, 0x64, 0x6a, 0xe2, 0x62, 0xd3, 0x2c, 0xa5, 0x5d, 0x16, 0x69, 0xef, 0x68,
	0xb7, 0x72, 0xf3, 0x75, 0x6b, 0x7f, 0x1f, 0x36, 0x33, 0xd7, 0x66, 0x94, 0x87, 0xdc, 0xf9, 0xe9,
	0xea, 0x12, 0xd2, 0x60, 0xf9, 0xc4, 0x30, 0xce, 0x8d, 0x55, 0xa5, 0xf6, 0x67, 0x1e, 0x8a, 0xa1,
	0x71, 0x93, 0x75, 0x50, 0x13, 0x8a, 0x23, 0x2b, 0x18, 0xda, 0x89, 0x83, 0xa5, 0x77, 0x3e, 0x7d,
	0x77, 0x82, 0xd6, 0x4f, 0x18, 0x2f, 0xa1, 0x1f, 0x60, 0x2d, 0xb5, 0x40, 0x20, 0x1c, 0x7b, 0x4d,
	0xda, 0xd0, 0xf4, 0xe7, 0x53, 0x6d, 0x22, 0x7c, 0x57, 0x76, 0x28, 0x6b, 0x41, 0x41, 0x95, 0x29,
	0x08, 0x89, 0xe7, 0x5b, 0x7f, 0x31, 0x87, 0x65, 0x14, 0xd1, 0x92, 0x87, 0x7f, 0x7c, 0xb3, 0x40,
	0xef, 0x26, 0x30, 0x26, 0x6c, 0x2b, 0xfa, 0x7b, 0x33, 0xac, 0xa2, 0x28, 0x3d, 0x7f, 0xd7, 0x48,
	0xbf, 0x05, 0x68, 0x2f, 0x01, 0x31, 0xf9, 0x99, 0xd1, 0x2b, 0xb3, 0x0d, 0xa3, 0x70, 0x3f, 0xc2,
	0x66, 0xe6, 0x4b, 0x88, 0xde, 0x4f, 0x80, 0x4c, 0x7c, 0x61, 0xf5, 0xbd, 0x99, 0x76, 0x51, 0xac,
	0xef, 0x61, 0x75, 0x7c, 0x55, 0x40, 0xcf, 0x92, 0x5c, 0x33, 0xf6, 0x12, 0x1d, 0x4f, 0x33, 0x89,
	0xc0, 0x5f, 0xc2, 0xa3, 0xb1, 0xad, 0x0a, 0x95, 0x33, 0x1d, 0x47, 0xfb, 0xff, 0x6c, 0x8a, 0x45,
	0x88, 0x5c, 0xfb, 0x3d, 0x17, 0x9f, 0x93, 0x33, 0xe2, 0xa2, 0x26, 0x68, 0x91, 0x31, 0xda, 0x4d,
	0x20, 0x8c, 0xdf, 0x92, 0xfa, 0x93, 0x49, 0xea, 0x88, 0x77, 0x13, 0xb4, 0x56, 0x16, 0x5a, 0x6b,
	0x3a, 0x5a, 0x2b, 0x1b, 0xcd, 0x2f, 0x71, 0xe2, 0x72, 0x18, 0x2b, 0x71, 0xd6, 0x9d, 0x36, 0x56,
	0xe2, 0xcc, 0x3b, 0x0c, 0x2f, 0x1d, 0x1d, 0xc0, 0xe3, 0x36, 0xeb, 0x55, 0xfd, 0xff, 0xfa, 0xd5,
	0xe4, 0x5f, 0xfc, 0xa3, 0xd5, 0x91, 0x7b, 0x47, 0xee, 0x68, 0x17, 0xca, 0x55, 0x5e, 0xaa, 0x0e,
	0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x2a, 0xc0, 0x03, 0x63, 0x10, 0x00, 0x00,
}
