// Code generated by protoc-gen-go.
// source: trillian_api.proto
// DO NOT EDIT!

/*
Package trillian is a generated protocol buffer package.

It is generated from these files:
	trillian_api.proto
	trillian.proto

It has these top-level messages:
	TrillianApiStatus
	LeafProto
	QueueLeavesRequest
	QueueLeavesResponse
	GetInclusionProofRequest
	GetInclusionProofResponse
	GetConsistencyProofRequest
	GetConsistencyProofResponse
	GetLeavesByHashRequest
	GetLeavesByHashResponse
	GetLeavesByIndexRequest
	GetLeavesByIndexResponse
	GetSequencedLeafCountRequest
	GetSequencedLeafCountResponse
	GetLatestSignedLogRootRequest
	GetLatestSignedLogRootResponse
	DigitallySigned
	SignedEntryTimestamp
	SignedLogRoot
	SignedMapRoot
*/
package trillian

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TrillianApiStatusCode is an application level status code
type TrillianApiStatusCode int32

const (
	TrillianApiStatusCode_OK    TrillianApiStatusCode = 0
	TrillianApiStatusCode_ERROR TrillianApiStatusCode = 1
)

var TrillianApiStatusCode_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}
var TrillianApiStatusCode_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x TrillianApiStatusCode) Enum() *TrillianApiStatusCode {
	p := new(TrillianApiStatusCode)
	*p = x
	return p
}
func (x TrillianApiStatusCode) String() string {
	return proto.EnumName(TrillianApiStatusCode_name, int32(x))
}
func (x *TrillianApiStatusCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TrillianApiStatusCode_value, data, "TrillianApiStatusCode")
	if err != nil {
		return err
	}
	*x = TrillianApiStatusCode(value)
	return nil
}
func (TrillianApiStatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// All operations return a TrillianApiStatus.
// TODO(Martin2112): Most of the operations are not fully defined yet. They will be implemented soon
type TrillianApiStatus struct {
	// The status code indicates the overall result of the operation.
	StatusCode *TrillianApiStatusCode `protobuf:"varint,1,opt,name=status_code,enum=trillian.TrillianApiStatusCode" json:"status_code,omitempty"`
	// Applications should not make assumptions about the contents of description. They
	// should use status_code only when making error handling decisions.
	Description      *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TrillianApiStatus) Reset()                    { *m = TrillianApiStatus{} }
func (m *TrillianApiStatus) String() string            { return proto.CompactTextString(m) }
func (*TrillianApiStatus) ProtoMessage()               {}
func (*TrillianApiStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TrillianApiStatus) GetStatusCode() TrillianApiStatusCode {
	if m != nil && m.StatusCode != nil {
		return *m.StatusCode
	}
	return TrillianApiStatusCode_OK
}

func (m *TrillianApiStatus) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type LeafProto struct {
	LeafHash         []byte `protobuf:"bytes,1,opt,name=leaf_hash" json:"leaf_hash,omitempty"`
	LeafData         []byte `protobuf:"bytes,2,opt,name=leaf_data" json:"leaf_data,omitempty"`
	ExtraData        []byte `protobuf:"bytes,3,opt,name=extra_data" json:"extra_data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LeafProto) Reset()                    { *m = LeafProto{} }
func (m *LeafProto) String() string            { return proto.CompactTextString(m) }
func (*LeafProto) ProtoMessage()               {}
func (*LeafProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LeafProto) GetLeafHash() []byte {
	if m != nil {
		return m.LeafHash
	}
	return nil
}

func (m *LeafProto) GetLeafData() []byte {
	if m != nil {
		return m.LeafData
	}
	return nil
}

func (m *LeafProto) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

type QueueLeavesRequest struct {
	LogId            *int64       `protobuf:"varint,1,opt,name=log_id" json:"log_id,omitempty"`
	Leaves           []*LeafProto `protobuf:"bytes,2,rep,name=leaves" json:"leaves,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *QueueLeavesRequest) Reset()                    { *m = QueueLeavesRequest{} }
func (m *QueueLeavesRequest) String() string            { return proto.CompactTextString(m) }
func (*QueueLeavesRequest) ProtoMessage()               {}
func (*QueueLeavesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueueLeavesRequest) GetLogId() int64 {
	if m != nil && m.LogId != nil {
		return *m.LogId
	}
	return 0
}

func (m *QueueLeavesRequest) GetLeaves() []*LeafProto {
	if m != nil {
		return m.Leaves
	}
	return nil
}

// TODO(Martin2112): This will eventually contain the signed timestamps and stuff that we return for
// the queued leaves
type QueueLeavesResponse struct {
	Status           *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *QueueLeavesResponse) Reset()                    { *m = QueueLeavesResponse{} }
func (m *QueueLeavesResponse) String() string            { return proto.CompactTextString(m) }
func (*QueueLeavesResponse) ProtoMessage()               {}
func (*QueueLeavesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueueLeavesResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetInclusionProofRequest struct {
	LogId            *int64 `protobuf:"varint,1,opt,name=log_id" json:"log_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetInclusionProofRequest) Reset()                    { *m = GetInclusionProofRequest{} }
func (m *GetInclusionProofRequest) String() string            { return proto.CompactTextString(m) }
func (*GetInclusionProofRequest) ProtoMessage()               {}
func (*GetInclusionProofRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetInclusionProofRequest) GetLogId() int64 {
	if m != nil && m.LogId != nil {
		return *m.LogId
	}
	return 0
}

type GetInclusionProofResponse struct {
	Status           *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GetInclusionProofResponse) Reset()                    { *m = GetInclusionProofResponse{} }
func (m *GetInclusionProofResponse) String() string            { return proto.CompactTextString(m) }
func (*GetInclusionProofResponse) ProtoMessage()               {}
func (*GetInclusionProofResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetInclusionProofResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetConsistencyProofRequest struct {
	LogId            *int64 `protobuf:"varint,1,opt,name=log_id" json:"log_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetConsistencyProofRequest) Reset()                    { *m = GetConsistencyProofRequest{} }
func (m *GetConsistencyProofRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConsistencyProofRequest) ProtoMessage()               {}
func (*GetConsistencyProofRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetConsistencyProofRequest) GetLogId() int64 {
	if m != nil && m.LogId != nil {
		return *m.LogId
	}
	return 0
}

type GetConsistencyProofResponse struct {
	Status           *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GetConsistencyProofResponse) Reset()                    { *m = GetConsistencyProofResponse{} }
func (m *GetConsistencyProofResponse) String() string            { return proto.CompactTextString(m) }
func (*GetConsistencyProofResponse) ProtoMessage()               {}
func (*GetConsistencyProofResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetConsistencyProofResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetLeavesByHashRequest struct {
	LogId            *int64   `protobuf:"varint,1,opt,name=log_id" json:"log_id,omitempty"`
	LeafHash         [][]byte `protobuf:"bytes,2,rep,name=leaf_hash" json:"leaf_hash,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetLeavesByHashRequest) Reset()                    { *m = GetLeavesByHashRequest{} }
func (m *GetLeavesByHashRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLeavesByHashRequest) ProtoMessage()               {}
func (*GetLeavesByHashRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetLeavesByHashRequest) GetLogId() int64 {
	if m != nil && m.LogId != nil {
		return *m.LogId
	}
	return 0
}

func (m *GetLeavesByHashRequest) GetLeafHash() [][]byte {
	if m != nil {
		return m.LeafHash
	}
	return nil
}

type GetLeavesByHashResponse struct {
	Status           *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GetLeavesByHashResponse) Reset()                    { *m = GetLeavesByHashResponse{} }
func (m *GetLeavesByHashResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLeavesByHashResponse) ProtoMessage()               {}
func (*GetLeavesByHashResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetLeavesByHashResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetLeavesByIndexRequest struct {
	LogId            *int64  `protobuf:"varint,1,opt,name=log_id" json:"log_id,omitempty"`
	LeafIndex        []int64 `protobuf:"varint,2,rep,name=leaf_index" json:"leaf_index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetLeavesByIndexRequest) Reset()                    { *m = GetLeavesByIndexRequest{} }
func (m *GetLeavesByIndexRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLeavesByIndexRequest) ProtoMessage()               {}
func (*GetLeavesByIndexRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetLeavesByIndexRequest) GetLogId() int64 {
	if m != nil && m.LogId != nil {
		return *m.LogId
	}
	return 0
}

func (m *GetLeavesByIndexRequest) GetLeafIndex() []int64 {
	if m != nil {
		return m.LeafIndex
	}
	return nil
}

type GetLeavesByIndexResponse struct {
	Status           *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Leaves           []*LeafProto       `protobuf:"bytes,2,rep,name=leaves" json:"leaves,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GetLeavesByIndexResponse) Reset()                    { *m = GetLeavesByIndexResponse{} }
func (m *GetLeavesByIndexResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLeavesByIndexResponse) ProtoMessage()               {}
func (*GetLeavesByIndexResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetLeavesByIndexResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetLeavesByIndexResponse) GetLeaves() []*LeafProto {
	if m != nil {
		return m.Leaves
	}
	return nil
}

type GetSequencedLeafCountRequest struct {
	LogId            *int64 `protobuf:"varint,1,opt,name=log_id" json:"log_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetSequencedLeafCountRequest) Reset()                    { *m = GetSequencedLeafCountRequest{} }
func (m *GetSequencedLeafCountRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSequencedLeafCountRequest) ProtoMessage()               {}
func (*GetSequencedLeafCountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetSequencedLeafCountRequest) GetLogId() int64 {
	if m != nil && m.LogId != nil {
		return *m.LogId
	}
	return 0
}

type GetSequencedLeafCountResponse struct {
	Status           *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GetSequencedLeafCountResponse) Reset()                    { *m = GetSequencedLeafCountResponse{} }
func (m *GetSequencedLeafCountResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSequencedLeafCountResponse) ProtoMessage()               {}
func (*GetSequencedLeafCountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetSequencedLeafCountResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetLatestSignedLogRootRequest struct {
	LogId            *int64 `protobuf:"varint,1,opt,name=log_id" json:"log_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetLatestSignedLogRootRequest) Reset()                    { *m = GetLatestSignedLogRootRequest{} }
func (m *GetLatestSignedLogRootRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLatestSignedLogRootRequest) ProtoMessage()               {}
func (*GetLatestSignedLogRootRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetLatestSignedLogRootRequest) GetLogId() int64 {
	if m != nil && m.LogId != nil {
		return *m.LogId
	}
	return 0
}

type GetLatestSignedLogRootResponse struct {
	Status           *TrillianApiStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	SignedLogRoot    *SignedLogRoot     `protobuf:"bytes,2,opt,name=signed_log_root" json:"signed_log_root,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GetLatestSignedLogRootResponse) Reset()                    { *m = GetLatestSignedLogRootResponse{} }
func (m *GetLatestSignedLogRootResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLatestSignedLogRootResponse) ProtoMessage()               {}
func (*GetLatestSignedLogRootResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetLatestSignedLogRootResponse) GetStatus() *TrillianApiStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetLatestSignedLogRootResponse) GetSignedLogRoot() *SignedLogRoot {
	if m != nil {
		return m.SignedLogRoot
	}
	return nil
}

func init() {
	proto.RegisterType((*TrillianApiStatus)(nil), "trillian.TrillianApiStatus")
	proto.RegisterType((*LeafProto)(nil), "trillian.LeafProto")
	proto.RegisterType((*QueueLeavesRequest)(nil), "trillian.QueueLeavesRequest")
	proto.RegisterType((*QueueLeavesResponse)(nil), "trillian.QueueLeavesResponse")
	proto.RegisterType((*GetInclusionProofRequest)(nil), "trillian.GetInclusionProofRequest")
	proto.RegisterType((*GetInclusionProofResponse)(nil), "trillian.GetInclusionProofResponse")
	proto.RegisterType((*GetConsistencyProofRequest)(nil), "trillian.GetConsistencyProofRequest")
	proto.RegisterType((*GetConsistencyProofResponse)(nil), "trillian.GetConsistencyProofResponse")
	proto.RegisterType((*GetLeavesByHashRequest)(nil), "trillian.GetLeavesByHashRequest")
	proto.RegisterType((*GetLeavesByHashResponse)(nil), "trillian.GetLeavesByHashResponse")
	proto.RegisterType((*GetLeavesByIndexRequest)(nil), "trillian.GetLeavesByIndexRequest")
	proto.RegisterType((*GetLeavesByIndexResponse)(nil), "trillian.GetLeavesByIndexResponse")
	proto.RegisterType((*GetSequencedLeafCountRequest)(nil), "trillian.GetSequencedLeafCountRequest")
	proto.RegisterType((*GetSequencedLeafCountResponse)(nil), "trillian.GetSequencedLeafCountResponse")
	proto.RegisterType((*GetLatestSignedLogRootRequest)(nil), "trillian.GetLatestSignedLogRootRequest")
	proto.RegisterType((*GetLatestSignedLogRootResponse)(nil), "trillian.GetLatestSignedLogRootResponse")
	proto.RegisterEnum("trillian.TrillianApiStatusCode", TrillianApiStatusCode_name, TrillianApiStatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for TrillianLog service

type TrillianLogClient interface {
	// Corresponds to the LeafQueuer API
	QueueLeaves(ctx context.Context, in *QueueLeavesRequest, opts ...grpc.CallOption) (*QueueLeavesResponse, error)
	// No direct equivalent at the storage level
	GetInclusionProof(ctx context.Context, in *GetInclusionProofRequest, opts ...grpc.CallOption) (*GetInclusionProofResponse, error)
	GetConsistencyProof(ctx context.Context, in *GetConsistencyProofRequest, opts ...grpc.CallOption) (*GetConsistencyProofResponse, error)
	// Corresponds to the LogRootReader API
	GetLatestSignedLogRoot(ctx context.Context, in *GetLatestSignedLogRootRequest, opts ...grpc.CallOption) (*GetLatestSignedLogRootResponse, error)
	// Corresponds to the LeafReader API
	GetSequencedLeafCount(ctx context.Context, in *GetSequencedLeafCountRequest, opts ...grpc.CallOption) (*GetSequencedLeafCountResponse, error)
	GetLeavesByIndex(ctx context.Context, in *GetLeavesByIndexRequest, opts ...grpc.CallOption) (*GetLeavesByIndexResponse, error)
	GetLeavesByHash(ctx context.Context, in *GetLeavesByHashRequest, opts ...grpc.CallOption) (*GetLeavesByHashResponse, error)
}

type trillianLogClient struct {
	cc *grpc.ClientConn
}

func NewTrillianLogClient(cc *grpc.ClientConn) TrillianLogClient {
	return &trillianLogClient{cc}
}

func (c *trillianLogClient) QueueLeaves(ctx context.Context, in *QueueLeavesRequest, opts ...grpc.CallOption) (*QueueLeavesResponse, error) {
	out := new(QueueLeavesResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/QueueLeaves", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianLogClient) GetInclusionProof(ctx context.Context, in *GetInclusionProofRequest, opts ...grpc.CallOption) (*GetInclusionProofResponse, error) {
	out := new(GetInclusionProofResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/GetInclusionProof", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianLogClient) GetConsistencyProof(ctx context.Context, in *GetConsistencyProofRequest, opts ...grpc.CallOption) (*GetConsistencyProofResponse, error) {
	out := new(GetConsistencyProofResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/GetConsistencyProof", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianLogClient) GetLatestSignedLogRoot(ctx context.Context, in *GetLatestSignedLogRootRequest, opts ...grpc.CallOption) (*GetLatestSignedLogRootResponse, error) {
	out := new(GetLatestSignedLogRootResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/GetLatestSignedLogRoot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianLogClient) GetSequencedLeafCount(ctx context.Context, in *GetSequencedLeafCountRequest, opts ...grpc.CallOption) (*GetSequencedLeafCountResponse, error) {
	out := new(GetSequencedLeafCountResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/GetSequencedLeafCount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianLogClient) GetLeavesByIndex(ctx context.Context, in *GetLeavesByIndexRequest, opts ...grpc.CallOption) (*GetLeavesByIndexResponse, error) {
	out := new(GetLeavesByIndexResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/GetLeavesByIndex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trillianLogClient) GetLeavesByHash(ctx context.Context, in *GetLeavesByHashRequest, opts ...grpc.CallOption) (*GetLeavesByHashResponse, error) {
	out := new(GetLeavesByHashResponse)
	err := grpc.Invoke(ctx, "/trillian.TrillianLog/GetLeavesByHash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TrillianLog service

type TrillianLogServer interface {
	// Corresponds to the LeafQueuer API
	QueueLeaves(context.Context, *QueueLeavesRequest) (*QueueLeavesResponse, error)
	// No direct equivalent at the storage level
	GetInclusionProof(context.Context, *GetInclusionProofRequest) (*GetInclusionProofResponse, error)
	GetConsistencyProof(context.Context, *GetConsistencyProofRequest) (*GetConsistencyProofResponse, error)
	// Corresponds to the LogRootReader API
	GetLatestSignedLogRoot(context.Context, *GetLatestSignedLogRootRequest) (*GetLatestSignedLogRootResponse, error)
	// Corresponds to the LeafReader API
	GetSequencedLeafCount(context.Context, *GetSequencedLeafCountRequest) (*GetSequencedLeafCountResponse, error)
	GetLeavesByIndex(context.Context, *GetLeavesByIndexRequest) (*GetLeavesByIndexResponse, error)
	GetLeavesByHash(context.Context, *GetLeavesByHashRequest) (*GetLeavesByHashResponse, error)
}

func RegisterTrillianLogServer(s *grpc.Server, srv TrillianLogServer) {
	s.RegisterService(&_TrillianLog_serviceDesc, srv)
}

func _TrillianLog_QueueLeaves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueLeavesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).QueueLeaves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/QueueLeaves",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).QueueLeaves(ctx, req.(*QueueLeavesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianLog_GetInclusionProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInclusionProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).GetInclusionProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/GetInclusionProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).GetInclusionProof(ctx, req.(*GetInclusionProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianLog_GetConsistencyProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsistencyProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).GetConsistencyProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/GetConsistencyProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).GetConsistencyProof(ctx, req.(*GetConsistencyProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianLog_GetLatestSignedLogRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestSignedLogRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).GetLatestSignedLogRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/GetLatestSignedLogRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).GetLatestSignedLogRoot(ctx, req.(*GetLatestSignedLogRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianLog_GetSequencedLeafCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSequencedLeafCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).GetSequencedLeafCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/GetSequencedLeafCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).GetSequencedLeafCount(ctx, req.(*GetSequencedLeafCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianLog_GetLeavesByIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeavesByIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).GetLeavesByIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/GetLeavesByIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).GetLeavesByIndex(ctx, req.(*GetLeavesByIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrillianLog_GetLeavesByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeavesByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrillianLogServer).GetLeavesByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trillian.TrillianLog/GetLeavesByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrillianLogServer).GetLeavesByHash(ctx, req.(*GetLeavesByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrillianLog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trillian.TrillianLog",
	HandlerType: (*TrillianLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueueLeaves",
			Handler:    _TrillianLog_QueueLeaves_Handler,
		},
		{
			MethodName: "GetInclusionProof",
			Handler:    _TrillianLog_GetInclusionProof_Handler,
		},
		{
			MethodName: "GetConsistencyProof",
			Handler:    _TrillianLog_GetConsistencyProof_Handler,
		},
		{
			MethodName: "GetLatestSignedLogRoot",
			Handler:    _TrillianLog_GetLatestSignedLogRoot_Handler,
		},
		{
			MethodName: "GetSequencedLeafCount",
			Handler:    _TrillianLog_GetSequencedLeafCount_Handler,
		},
		{
			MethodName: "GetLeavesByIndex",
			Handler:    _TrillianLog_GetLeavesByIndex_Handler,
		},
		{
			MethodName: "GetLeavesByHash",
			Handler:    _TrillianLog_GetLeavesByHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("trillian_api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x55, 0xef, 0x6f, 0xd2, 0x4e,
	0x18, 0x1f, 0x23, 0x23, 0x5f, 0x9e, 0x12, 0xc6, 0x1e, 0xb2, 0xef, 0x58, 0xb7, 0xe9, 0x76, 0x53,
	0x47, 0xd0, 0x30, 0x43, 0x7c, 0x67, 0x7c, 0x21, 0x64, 0x3a, 0x94, 0x64, 0x13, 0x7c, 0x61, 0x62,
	0x22, 0x69, 0xda, 0x1b, 0xab, 0xe9, 0x7a, 0xc8, 0x5d, 0xcd, 0xf6, 0xca, 0x3f, 0xca, 0x7f, 0xd0,
	0xeb, 0x55, 0x0a, 0x85, 0x1e, 0x98, 0xbe, 0xa3, 0xd7, 0xcf, 0xaf, 0xeb, 0xf3, 0x03, 0x40, 0x31,
	0x71, 0x3d, 0xcf, 0xb5, 0xfc, 0xa1, 0x35, 0x76, 0x9b, 0xe3, 0x09, 0x13, 0x0c, 0xff, 0x9b, 0x9e,
	0x99, 0xe5, 0xe9, 0xaf, 0xe8, 0x0d, 0xf9, 0x06, 0x3b, 0x9f, 0xff, 0x9e, 0xbc, 0x1d, 0xbb, 0x03,
	0x61, 0x89, 0x80, 0xe3, 0x2b, 0x30, 0xb8, 0xfa, 0x35, 0xb4, 0x99, 0x43, 0x6b, 0xb9, 0xe3, 0x5c,
	0xbd, 0xdc, 0x7a, 0xdc, 0x8c, 0xa9, 0x4b, 0x8c, 0x8e, 0x84, 0x61, 0x15, 0x0c, 0x87, 0x72, 0x7b,
	0xe2, 0x8e, 0x85, 0xcb, 0xfc, 0xda, 0xa6, 0x64, 0x15, 0xc9, 0x05, 0x14, 0x7b, 0xd4, 0xba, 0xb9,
	0x56, 0x31, 0x76, 0xa0, 0xe8, 0xc9, 0x87, 0xe1, 0xad, 0xc5, 0x6f, 0x95, 0x6a, 0x29, 0x3e, 0x72,
	0x2c, 0x61, 0x29, 0x4a, 0x09, 0x11, 0x80, 0xde, 0x8b, 0x89, 0x15, 0x9d, 0xe5, 0xc3, 0x33, 0xd2,
	0x05, 0xfc, 0x14, 0xd0, 0x80, 0x4a, 0xad, 0x9f, 0x94, 0xf7, 0xe9, 0x8f, 0x80, 0x72, 0x81, 0x65,
	0x28, 0x78, 0x6c, 0x34, 0x74, 0x1d, 0x25, 0x96, 0xc7, 0x53, 0xf9, 0xac, 0x00, 0x52, 0x29, 0x5f,
	0x37, 0x5a, 0xd5, 0x59, 0xe4, 0x38, 0x04, 0x69, 0x43, 0x35, 0x21, 0xc5, 0xc7, 0xcc, 0xe7, 0x14,
	0x9f, 0x43, 0x21, 0xba, 0xb3, 0xd2, 0x32, 0x5a, 0x07, 0x2b, 0xae, 0x4b, 0x1a, 0x50, 0x7b, 0x4f,
	0x45, 0xd7, 0xb7, 0xbd, 0x80, 0xcb, 0xbb, 0x4a, 0x61, 0x76, 0xa3, 0x09, 0x45, 0x2e, 0x61, 0x3f,
	0x05, 0x9b, 0xc5, 0xf5, 0x05, 0x98, 0x52, 0xa9, 0x23, 0x89, 0x2e, 0x17, 0xd4, 0xb7, 0x1f, 0x56,
	0xfa, 0x7e, 0x80, 0x83, 0x54, 0x74, 0x16, 0xe7, 0xd7, 0xf0, 0xbf, 0xd4, 0x8a, 0xbe, 0x58, 0xfb,
	0xe1, 0x52, 0x96, 0x4f, 0x57, 0x82, 0x44, 0x89, 0xc3, 0x2a, 0x94, 0xc8, 0x3b, 0xd8, 0x5b, 0x22,
	0x67, 0x09, 0xf1, 0x26, 0xa1, 0xd3, 0xf5, 0x1d, 0x7a, 0xaf, 0x4b, 0x21, 0x5b, 0x48, 0xa5, 0x70,
	0x43, 0x90, 0x8a, 0x91, 0x27, 0x9e, 0xaa, 0xd9, 0x02, 0x3d, 0x43, 0x8e, 0x7f, 0xeb, 0xb2, 0x26,
	0x1c, 0x4a, 0xb7, 0x41, 0x98, 0xcf, 0xb7, 0xa9, 0x13, 0xbe, 0xe8, 0xb0, 0xc0, 0x17, 0xba, 0x6a,
	0xf5, 0xe0, 0x48, 0x83, 0xcf, 0xf2, 0xa9, 0xce, 0x95, 0x5a, 0xcf, 0x12, 0xd2, 0x6a, 0xe0, 0x8e,
	0x7c, 0x29, 0xc8, 0x46, 0x7d, 0xc6, 0xb4, 0xf6, 0xbf, 0xe0, 0x91, 0x8e, 0x90, 0xe5, 0x13, 0xbd,
	0x84, 0x6d, 0xae, 0x54, 0x86, 0xa1, 0x8b, 0xec, 0x3b, 0xa1, 0x66, 0xdb, 0x68, 0xed, 0xcd, 0x58,
	0x09, 0x9b, 0x46, 0x03, 0x76, 0xd3, 0xb7, 0x4a, 0x01, 0x36, 0xaf, 0x3e, 0x56, 0x36, 0xb0, 0x08,
	0x5b, 0x17, 0xfd, 0xfe, 0x55, 0xbf, 0x92, 0x6b, 0xfd, 0xde, 0x02, 0x63, 0x0a, 0x96, 0x7c, 0xec,
	0x81, 0x31, 0x37, 0xd1, 0x78, 0x38, 0xf3, 0x58, 0xde, 0x19, 0xe6, 0x91, 0xe6, 0x6d, 0x74, 0x4d,
	0xb2, 0x81, 0x72, 0x23, 0x2e, 0xcd, 0x2b, 0x92, 0x19, 0x4b, 0x37, 0xf8, 0xe6, 0xe9, 0x4a, 0x4c,
	0xac, 0xef, 0x40, 0x35, 0x65, 0x2e, 0xf1, 0x49, 0x82, 0xad, 0x19, 0x72, 0xf3, 0xe9, 0x1a, 0x54,
	0xec, 0x72, 0x17, 0x4d, 0xec, 0x72, 0x41, 0xf1, 0x2c, 0x21, 0xa1, 0xef, 0x11, 0xb3, 0xbe, 0x1e,
	0x18, 0xdb, 0x7d, 0x87, 0xdd, 0xd4, 0xf6, 0xc5, 0x67, 0x09, 0x11, 0xed, 0x3c, 0x98, 0x67, 0x6b,
	0x71, 0xb1, 0xd7, 0x57, 0xa8, 0x2c, 0x0e, 0x32, 0x9e, 0x24, 0xb3, 0xa6, 0xec, 0x08, 0x93, 0xac,
	0x82, 0xc4, 0xe2, 0x5f, 0x60, 0x7b, 0x61, 0x59, 0xe1, 0x71, 0x2a, 0x71, 0x6e, 0x09, 0x9a, 0x27,
	0x2b, 0x10, 0x53, 0xe5, 0xf6, 0x39, 0xec, 0xdb, 0xec, 0xae, 0x39, 0x62, 0x6c, 0xe4, 0xd1, 0x66,
	0xf2, 0x6f, 0xb8, 0x5d, 0x99, 0x6b, 0x7e, 0xb5, 0x40, 0xae, 0x73, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x57, 0x46, 0xcf, 0x5b, 0xc9, 0x07, 0x00, 0x00,
}
