// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trillian.proto

package trillian

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import keyspb "github.com/google/trillian/crypto/keyspb"
import sigpb "github.com/google/trillian/crypto/sigpb"
import google_protobuf2 "github.com/golang/protobuf/ptypes/any"
import google_protobuf3 "github.com/golang/protobuf/ptypes/duration"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// LogRootFormat specifies the fields that are covered by the
// SignedLogRoot signature, as well as their ordering and formats.
type LogRootFormat int32

const (
	LogRootFormat_LOG_ROOT_FORMAT_UNKNOWN LogRootFormat = 0
	LogRootFormat_LOG_ROOT_FORMAT_V1      LogRootFormat = 1
)

var LogRootFormat_name = map[int32]string{
	0: "LOG_ROOT_FORMAT_UNKNOWN",
	1: "LOG_ROOT_FORMAT_V1",
}
var LogRootFormat_value = map[string]int32{
	"LOG_ROOT_FORMAT_UNKNOWN": 0,
	"LOG_ROOT_FORMAT_V1":      1,
}

func (x LogRootFormat) String() string {
	return proto.EnumName(LogRootFormat_name, int32(x))
}
func (LogRootFormat) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

// MapRootFormat specifies the fields that are covered by the
// SignedMapRoot signature, as well as their ordering and formats.
type MapRootFormat int32

const (
	MapRootFormat_MAP_ROOT_FORMAT_UNKNOWN MapRootFormat = 0
	MapRootFormat_MAP_ROOT_FORMAT_V1      MapRootFormat = 1
)

var MapRootFormat_name = map[int32]string{
	0: "MAP_ROOT_FORMAT_UNKNOWN",
	1: "MAP_ROOT_FORMAT_V1",
}
var MapRootFormat_value = map[string]int32{
	"MAP_ROOT_FORMAT_UNKNOWN": 0,
	"MAP_ROOT_FORMAT_V1":      1,
}

func (x MapRootFormat) String() string {
	return proto.EnumName(MapRootFormat_name, int32(x))
}
func (MapRootFormat) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

// Defines the way empty / node / leaf hashes are constructed incorporating
// preimage protection, which can be application specific.
type HashStrategy int32

const (
	// Hash strategy cannot be determined. Included to enable detection of
	// mismatched proto versions being used. Represents an invalid value.
	HashStrategy_UNKNOWN_HASH_STRATEGY HashStrategy = 0
	// Certificate Transparency strategy: leaf hash prefix = 0x00, node prefix =
	// 0x01, empty hash is digest([]byte{}), as defined in the specification.
	HashStrategy_RFC6962_SHA256 HashStrategy = 1
	// Sparse Merkle Tree strategy:  leaf hash prefix = 0x00, node prefix = 0x01,
	// empty branch is recursively computed from empty leaf nodes.
	// NOT secure in a multi tree environment. For testing only.
	HashStrategy_TEST_MAP_HASHER HashStrategy = 2
	// Append-only log strategy where leaf nodes are defined as the ObjectHash.
	// All other properties are equal to RFC6962_SHA256.
	HashStrategy_OBJECT_RFC6962_SHA256 HashStrategy = 3
	// The CONIKS sparse tree hasher with SHA512_256 as the hash algorithm.
	HashStrategy_CONIKS_SHA512_256 HashStrategy = 4
)

var HashStrategy_name = map[int32]string{
	0: "UNKNOWN_HASH_STRATEGY",
	1: "RFC6962_SHA256",
	2: "TEST_MAP_HASHER",
	3: "OBJECT_RFC6962_SHA256",
	4: "CONIKS_SHA512_256",
}
var HashStrategy_value = map[string]int32{
	"UNKNOWN_HASH_STRATEGY": 0,
	"RFC6962_SHA256":        1,
	"TEST_MAP_HASHER":       2,
	"OBJECT_RFC6962_SHA256": 3,
	"CONIKS_SHA512_256":     4,
}

func (x HashStrategy) String() string {
	return proto.EnumName(HashStrategy_name, int32(x))
}
func (HashStrategy) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

// State of the tree.
type TreeState int32

const (
	// Tree state cannot be determined. Included to enable detection of
	// mismatched proto versions being used. Represents an invalid value.
	TreeState_UNKNOWN_TREE_STATE TreeState = 0
	// Active trees are able to respond to both read and write requests.
	TreeState_ACTIVE TreeState = 1
	// Frozen trees are only able to respond to read requests, writing to a frozen
	// tree is forbidden. Trees should not be frozen when there are entries
	// in the queue that have not yet been integrated. See the DRAINING
	// state for this case.
	TreeState_FROZEN TreeState = 2
	// Deprecated in favor of Tree.deleted.
	TreeState_DEPRECATED_SOFT_DELETED TreeState = 3
	// Deprecated in favor of Tree.deleted.
	TreeState_DEPRECATED_HARD_DELETED TreeState = 4
	// A tree that is draining will continue to integrate queued entries.
	// No new entries should be accepted.
	TreeState_DRAINING TreeState = 5
)

var TreeState_name = map[int32]string{
	0: "UNKNOWN_TREE_STATE",
	1: "ACTIVE",
	2: "FROZEN",
	3: "DEPRECATED_SOFT_DELETED",
	4: "DEPRECATED_HARD_DELETED",
	5: "DRAINING",
}
var TreeState_value = map[string]int32{
	"UNKNOWN_TREE_STATE":      0,
	"ACTIVE":                  1,
	"FROZEN":                  2,
	"DEPRECATED_SOFT_DELETED": 3,
	"DEPRECATED_HARD_DELETED": 4,
	"DRAINING":                5,
}

func (x TreeState) String() string {
	return proto.EnumName(TreeState_name, int32(x))
}
func (TreeState) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

// Type of the tree.
type TreeType int32

const (
	// Tree type cannot be determined. Included to enable detection of mismatched
	// proto versions being used. Represents an invalid value.
	TreeType_UNKNOWN_TREE_TYPE TreeType = 0
	// Tree represents a verifiable log.
	TreeType_LOG TreeType = 1
	// Tree represents a verifiable map.
	TreeType_MAP TreeType = 2
	// Tree represents a verifiable pre-ordered log, i.e., a log whose entries are
	// placed according to sequence numbers assigned outside of Trillian.
	// TODO(pavelkalinnikov): Support this type.
	TreeType_PREORDERED_LOG TreeType = 3
)

var TreeType_name = map[int32]string{
	0: "UNKNOWN_TREE_TYPE",
	1: "LOG",
	2: "MAP",
	3: "PREORDERED_LOG",
}
var TreeType_value = map[string]int32{
	"UNKNOWN_TREE_TYPE": 0,
	"LOG":               1,
	"MAP":               2,
	"PREORDERED_LOG":    3,
}

func (x TreeType) String() string {
	return proto.EnumName(TreeType_name, int32(x))
}
func (TreeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

// Represents a tree, which may be either a verifiable log or map.
// Readonly attributes are assigned at tree creation, after which they may not
// be modified.
//
// Note: Many APIs within the rest of the code require these objects to
// be provided. For safety they should be obtained via Admin API calls and
// not created dynamically.
type Tree struct {
	// ID of the tree.
	// Readonly.
	TreeId int64 `protobuf:"varint,1,opt,name=tree_id,json=treeId" json:"tree_id,omitempty"`
	// State of the tree.
	// Trees are active after creation. At any point the tree may transition
	// between ACTIVE and FROZEN.
	TreeState TreeState `protobuf:"varint,2,opt,name=tree_state,json=treeState,enum=trillian.TreeState" json:"tree_state,omitempty"`
	// Type of the tree.
	// Readonly.
	TreeType TreeType `protobuf:"varint,3,opt,name=tree_type,json=treeType,enum=trillian.TreeType" json:"tree_type,omitempty"`
	// Hash strategy to be used by the tree.
	// Readonly.
	HashStrategy HashStrategy `protobuf:"varint,4,opt,name=hash_strategy,json=hashStrategy,enum=trillian.HashStrategy" json:"hash_strategy,omitempty"`
	// Hash algorithm to be used by the tree.
	// Readonly.
	HashAlgorithm sigpb.DigitallySigned_HashAlgorithm `protobuf:"varint,5,opt,name=hash_algorithm,json=hashAlgorithm,enum=sigpb.DigitallySigned_HashAlgorithm" json:"hash_algorithm,omitempty"`
	// Signature algorithm to be used by the tree.
	// Readonly.
	SignatureAlgorithm sigpb.DigitallySigned_SignatureAlgorithm `protobuf:"varint,6,opt,name=signature_algorithm,json=signatureAlgorithm,enum=sigpb.DigitallySigned_SignatureAlgorithm" json:"signature_algorithm,omitempty"`
	// Display name of the tree.
	// Optional.
	DisplayName string `protobuf:"bytes,8,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	// Description of the tree,
	// Optional.
	Description string `protobuf:"bytes,9,opt,name=description" json:"description,omitempty"`
	// Identifies the private key used for signing tree heads and entry
	// timestamps.
	// This can be any type of message to accommodate different key management
	// systems, e.g. PEM files, HSMs, etc.
	// Private keys are write-only: they're never returned by RPCs.
	// The private_key message can be changed after a tree is created, but the
	// underlying key must remain the same - this is to enable migrating a key
	// from one provider to another.
	PrivateKey *google_protobuf2.Any `protobuf:"bytes,12,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	// Storage-specific settings.
	// Varies according to the storage implementation backing Trillian.
	StorageSettings *google_protobuf2.Any `protobuf:"bytes,13,opt,name=storage_settings,json=storageSettings" json:"storage_settings,omitempty"`
	// The public key used for verifying tree heads and entry timestamps.
	// Readonly.
	PublicKey *keyspb.PublicKey `protobuf:"bytes,14,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	// Interval after which a new signed root is produced even if there have been
	// no submission.  If zero, this behavior is disabled.
	MaxRootDuration *google_protobuf3.Duration `protobuf:"bytes,15,opt,name=max_root_duration,json=maxRootDuration" json:"max_root_duration,omitempty"`
	// Time of tree creation.
	// Readonly.
	CreateTime *google_protobuf1.Timestamp `protobuf:"bytes,16,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	// Time of last tree update.
	// Readonly (automatically assigned on updates).
	UpdateTime *google_protobuf1.Timestamp `protobuf:"bytes,17,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	// If true, the tree has been deleted.
	// Deleted trees may be undeleted during a certain time window, after which
	// they're permanently deleted (and unrecoverable).
	// Readonly.
	Deleted bool `protobuf:"varint,19,opt,name=deleted" json:"deleted,omitempty"`
	// Time of tree deletion, if any.
	// Readonly.
	DeleteTime *google_protobuf1.Timestamp `protobuf:"bytes,20,opt,name=delete_time,json=deleteTime" json:"delete_time,omitempty"`
}

func (m *Tree) Reset()                    { *m = Tree{} }
func (m *Tree) String() string            { return proto.CompactTextString(m) }
func (*Tree) ProtoMessage()               {}
func (*Tree) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Tree) GetTreeId() int64 {
	if m != nil {
		return m.TreeId
	}
	return 0
}

func (m *Tree) GetTreeState() TreeState {
	if m != nil {
		return m.TreeState
	}
	return TreeState_UNKNOWN_TREE_STATE
}

func (m *Tree) GetTreeType() TreeType {
	if m != nil {
		return m.TreeType
	}
	return TreeType_UNKNOWN_TREE_TYPE
}

func (m *Tree) GetHashStrategy() HashStrategy {
	if m != nil {
		return m.HashStrategy
	}
	return HashStrategy_UNKNOWN_HASH_STRATEGY
}

func (m *Tree) GetHashAlgorithm() sigpb.DigitallySigned_HashAlgorithm {
	if m != nil {
		return m.HashAlgorithm
	}
	return sigpb.DigitallySigned_NONE
}

func (m *Tree) GetSignatureAlgorithm() sigpb.DigitallySigned_SignatureAlgorithm {
	if m != nil {
		return m.SignatureAlgorithm
	}
	return sigpb.DigitallySigned_ANONYMOUS
}

func (m *Tree) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Tree) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Tree) GetPrivateKey() *google_protobuf2.Any {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *Tree) GetStorageSettings() *google_protobuf2.Any {
	if m != nil {
		return m.StorageSettings
	}
	return nil
}

func (m *Tree) GetPublicKey() *keyspb.PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Tree) GetMaxRootDuration() *google_protobuf3.Duration {
	if m != nil {
		return m.MaxRootDuration
	}
	return nil
}

func (m *Tree) GetCreateTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Tree) GetUpdateTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Tree) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Tree) GetDeleteTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.DeleteTime
	}
	return nil
}

type SignedEntryTimestamp struct {
	TimestampNanos int64                  `protobuf:"varint,1,opt,name=timestamp_nanos,json=timestampNanos" json:"timestamp_nanos,omitempty"`
	LogId          int64                  `protobuf:"varint,2,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	Signature      *sigpb.DigitallySigned `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
}

func (m *SignedEntryTimestamp) Reset()                    { *m = SignedEntryTimestamp{} }
func (m *SignedEntryTimestamp) String() string            { return proto.CompactTextString(m) }
func (*SignedEntryTimestamp) ProtoMessage()               {}
func (*SignedEntryTimestamp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *SignedEntryTimestamp) GetTimestampNanos() int64 {
	if m != nil {
		return m.TimestampNanos
	}
	return 0
}

func (m *SignedEntryTimestamp) GetLogId() int64 {
	if m != nil {
		return m.LogId
	}
	return 0
}

func (m *SignedEntryTimestamp) GetSignature() *sigpb.DigitallySigned {
	if m != nil {
		return m.Signature
	}
	return nil
}

// SignedLogRoot represents a commitment by a Log to a particular tree.
type SignedLogRoot struct {
	// epoch nanoseconds, good until 2500ish
	TimestampNanos int64  `protobuf:"varint,1,opt,name=timestamp_nanos,json=timestampNanos" json:"timestamp_nanos,omitempty"`
	RootHash       []byte `protobuf:"bytes,2,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	// TreeSize is the number of entries in the tree.
	TreeSize     int64                  `protobuf:"varint,3,opt,name=tree_size,json=treeSize" json:"tree_size,omitempty"`
	Signature    *sigpb.DigitallySigned `protobuf:"bytes,4,opt,name=signature" json:"signature,omitempty"`
	TreeRevision int64                  `protobuf:"varint,6,opt,name=tree_revision,json=treeRevision" json:"tree_revision,omitempty"`
	KeyHint      []byte                 `protobuf:"bytes,7,opt,name=key_hint,json=keyHint,proto3" json:"key_hint,omitempty"`
}

func (m *SignedLogRoot) Reset()                    { *m = SignedLogRoot{} }
func (m *SignedLogRoot) String() string            { return proto.CompactTextString(m) }
func (*SignedLogRoot) ProtoMessage()               {}
func (*SignedLogRoot) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *SignedLogRoot) GetTimestampNanos() int64 {
	if m != nil {
		return m.TimestampNanos
	}
	return 0
}

func (m *SignedLogRoot) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *SignedLogRoot) GetTreeSize() int64 {
	if m != nil {
		return m.TreeSize
	}
	return 0
}

func (m *SignedLogRoot) GetSignature() *sigpb.DigitallySigned {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedLogRoot) GetTreeRevision() int64 {
	if m != nil {
		return m.TreeRevision
	}
	return 0
}

func (m *SignedLogRoot) GetKeyHint() []byte {
	if m != nil {
		return m.KeyHint
	}
	return nil
}

// SignedMapRoot represents a commitment by a Map to a particular tree.
type SignedMapRoot struct {
	TimestampNanos int64  `protobuf:"varint,1,opt,name=timestamp_nanos,json=timestampNanos" json:"timestamp_nanos,omitempty"`
	RootHash       []byte `protobuf:"bytes,2,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	// TODO(al): define serialized format for the signature scheme.
	Signature   *sigpb.DigitallySigned `protobuf:"bytes,4,opt,name=signature" json:"signature,omitempty"`
	MapId       int64                  `protobuf:"varint,5,opt,name=map_id,json=mapId" json:"map_id,omitempty"`
	MapRevision int64                  `protobuf:"varint,6,opt,name=map_revision,json=mapRevision" json:"map_revision,omitempty"`
	// Metadata associated with the Map root.  This is set by the map personality
	// layer in a SetLeaves map request.  It could be used to persist state
	// needed to recreate the Map from an external data source.
	Metadata *google_protobuf2.Any `protobuf:"bytes,7,opt,name=metadata" json:"metadata,omitempty"`
}

func (m *SignedMapRoot) Reset()                    { *m = SignedMapRoot{} }
func (m *SignedMapRoot) String() string            { return proto.CompactTextString(m) }
func (*SignedMapRoot) ProtoMessage()               {}
func (*SignedMapRoot) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *SignedMapRoot) GetTimestampNanos() int64 {
	if m != nil {
		return m.TimestampNanos
	}
	return 0
}

func (m *SignedMapRoot) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *SignedMapRoot) GetSignature() *sigpb.DigitallySigned {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedMapRoot) GetMapId() int64 {
	if m != nil {
		return m.MapId
	}
	return 0
}

func (m *SignedMapRoot) GetMapRevision() int64 {
	if m != nil {
		return m.MapRevision
	}
	return 0
}

func (m *SignedMapRoot) GetMetadata() *google_protobuf2.Any {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*Tree)(nil), "trillian.Tree")
	proto.RegisterType((*SignedEntryTimestamp)(nil), "trillian.SignedEntryTimestamp")
	proto.RegisterType((*SignedLogRoot)(nil), "trillian.SignedLogRoot")
	proto.RegisterType((*SignedMapRoot)(nil), "trillian.SignedMapRoot")
	proto.RegisterEnum("trillian.LogRootFormat", LogRootFormat_name, LogRootFormat_value)
	proto.RegisterEnum("trillian.MapRootFormat", MapRootFormat_name, MapRootFormat_value)
	proto.RegisterEnum("trillian.HashStrategy", HashStrategy_name, HashStrategy_value)
	proto.RegisterEnum("trillian.TreeState", TreeState_name, TreeState_value)
	proto.RegisterEnum("trillian.TreeType", TreeType_name, TreeType_value)
}

func init() { proto.RegisterFile("trillian.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 1082 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4b, 0x6f, 0xdb, 0x46,
	0x10, 0x0e, 0x25, 0x5a, 0xa2, 0x46, 0x0f, 0xd3, 0xeb, 0x38, 0xa1, 0x15, 0xa0, 0x51, 0xdd, 0x02,
	0x75, 0x73, 0x90, 0x13, 0xb5, 0x09, 0x50, 0xe4, 0x50, 0x30, 0x16, 0x6d, 0x49, 0xb6, 0x25, 0x61,
	0xc9, 0xa6, 0x48, 0x2e, 0xc4, 0x4a, 0xdc, 0x52, 0x84, 0xc5, 0x07, 0xc8, 0x55, 0x10, 0xe6, 0xdc,
	0x4b, 0xd1, 0xfe, 0xd6, 0xfe, 0x83, 0x02, 0xc5, 0x2e, 0x1f, 0x8e, 0x95, 0xa6, 0x09, 0x8a, 0x5e,
	0xa4, 0x9d, 0x99, 0xef, 0xfb, 0x76, 0x86, 0x33, 0xbb, 0x24, 0x74, 0x58, 0xec, 0xad, 0xd7, 0x1e,
	0x09, 0xfa, 0x51, 0x1c, 0xb2, 0x10, 0x29, 0x85, 0xdd, 0xed, 0x2e, 0xe3, 0x34, 0x62, 0xe1, 0xc9,
	0x35, 0x4d, 0x93, 0x68, 0x91, 0xff, 0x65, 0xa8, 0xae, 0x96, 0xc7, 0x12, 0xcf, 0x8d, 0x16, 0xd9,
	0x6f, 0x1e, 0x39, 0x74, 0xc3, 0xd0, 0x5d, 0xd3, 0x13, 0x61, 0x2d, 0x36, 0xbf, 0x9c, 0x90, 0x20,
	0xcd, 0x43, 0x5f, 0x6c, 0x87, 0x9c, 0x4d, 0x4c, 0x98, 0x17, 0xe6, 0x5b, 0x77, 0x1f, 0x6e, 0xc7,
	0x99, 0xe7, 0xd3, 0x84, 0x11, 0x3f, 0xca, 0x00, 0x47, 0xbf, 0xd5, 0x41, 0xb6, 0x62, 0x4a, 0xd1,
	0x7d, 0xa8, 0xb3, 0x98, 0x52, 0xdb, 0x73, 0x34, 0xa9, 0x27, 0x1d, 0x57, 0x71, 0x8d, 0x9b, 0x63,
	0x07, 0x0d, 0x00, 0x44, 0x20, 0x61, 0x84, 0x51, 0xad, 0xd2, 0x93, 0x8e, 0x3b, 0x83, 0xfd, 0x7e,
	0x59, 0x22, 0x27, 0x9b, 0x3c, 0x84, 0x1b, 0xac, 0x58, 0xa2, 0x13, 0x10, 0x86, 0xcd, 0xd2, 0x88,
	0x6a, 0x55, 0x41, 0x41, 0xb7, 0x29, 0x56, 0x1a, 0x51, 0xac, 0xb0, 0x7c, 0x85, 0x9e, 0x43, 0x7b,
	0x45, 0x92, 0x95, 0x9d, 0xb0, 0x98, 0x30, 0xea, 0xa6, 0x9a, 0x2c, 0x48, 0xf7, 0x6e, 0x48, 0x23,
	0x92, 0xac, 0xcc, 0x3c, 0x8a, 0x5b, 0xab, 0xf7, 0x2c, 0x74, 0x01, 0x1d, 0x41, 0x26, 0x6b, 0x37,
	0x8c, 0x3d, 0xb6, 0xf2, 0xb5, 0x1d, 0xc1, 0xfe, 0xba, 0x9f, 0x3d, 0xc5, 0xa1, 0xe7, 0x7a, 0x8c,
	0xac, 0xd7, 0xa9, 0xe9, 0xb9, 0x01, 0x75, 0x84, 0x94, 0x5e, 0x60, 0xb1, 0xd8, 0xb8, 0x34, 0xd1,
	0x6b, 0xd8, 0x4f, 0x3c, 0x37, 0x20, 0x6c, 0x13, 0xd3, 0xf7, 0x14, 0x6b, 0x42, 0xf1, 0xdb, 0x8f,
	0x28, 0x9a, 0x05, 0xe3, 0x46, 0x16, 0x25, 0x1f, 0xf8, 0xd0, 0x97, 0xd0, 0x72, 0xbc, 0x24, 0x5a,
	0x93, 0xd4, 0x0e, 0x88, 0x4f, 0x35, 0xa5, 0x27, 0x1d, 0x37, 0x70, 0x33, 0xf7, 0x4d, 0x89, 0x4f,
	0x51, 0x0f, 0x9a, 0x0e, 0x4d, 0x96, 0xb1, 0x17, 0xf1, 0x2e, 0x6a, 0x8d, 0x1c, 0x71, 0xe3, 0x42,
	0x4f, 0xa1, 0x19, 0xc5, 0xde, 0x1b, 0xc2, 0xa8, 0x7d, 0x4d, 0x53, 0xad, 0xd5, 0x93, 0x8e, 0x9b,
	0x83, 0xbb, 0xfd, 0xac, 0xd1, 0xfd, 0xa2, 0xd1, 0x7d, 0x3d, 0x48, 0x31, 0xe4, 0xc0, 0x0b, 0x9a,
	0xa2, 0x1f, 0x41, 0x4d, 0x58, 0x18, 0x13, 0x97, 0xda, 0x09, 0x65, 0xcc, 0x0b, 0xdc, 0x44, 0x6b,
	0xff, 0x0b, 0x77, 0x37, 0x47, 0x9b, 0x39, 0x18, 0x3d, 0x06, 0x88, 0x36, 0x8b, 0xb5, 0xb7, 0x14,
	0xdb, 0x76, 0x04, 0x75, 0xaf, 0x9f, 0x8f, 0xf0, 0x5c, 0x44, 0x2e, 0x68, 0x8a, 0x1b, 0x51, 0xb1,
	0x44, 0x06, 0xec, 0xf9, 0xe4, 0xad, 0x1d, 0x87, 0x21, 0xb3, 0x8b, 0xb9, 0xd4, 0x76, 0x05, 0xf1,
	0xf0, 0x83, 0x3d, 0x87, 0x39, 0x00, 0xef, 0xfa, 0xe4, 0x2d, 0x0e, 0x43, 0x56, 0x38, 0xd0, 0x73,
	0x68, 0x2e, 0x63, 0xca, 0xeb, 0xe5, 0xc3, 0xab, 0xa9, 0x42, 0xa0, 0xfb, 0x81, 0x80, 0x55, 0x4c,
	0x36, 0x86, 0x0c, 0xce, 0x1d, 0x9c, 0xbc, 0x89, 0x9c, 0x92, 0xbc, 0xf7, 0x69, 0x72, 0x06, 0x17,
	0x64, 0x0d, 0xea, 0x0e, 0x5d, 0x53, 0x46, 0x1d, 0x6d, 0xbf, 0x27, 0x1d, 0x2b, 0xb8, 0x30, 0xb9,
	0x6c, 0xb6, 0xcc, 0x64, 0xef, 0x7e, 0x5a, 0x36, 0x83, 0x73, 0xc7, 0x44, 0x56, 0x90, 0xba, 0x3f,
	0x91, 0x95, 0xba, 0xaa, 0x4c, 0x64, 0x05, 0xd4, 0xe6, 0x44, 0x56, 0x9a, 0x6a, 0xeb, 0xe8, 0x0f,
	0x09, 0xee, 0x66, 0x03, 0x65, 0x04, 0x2c, 0x4e, 0x4b, 0x32, 0xfa, 0x06, 0x76, 0xcb, 0x73, 0x6b,
	0x07, 0x24, 0x08, 0x93, 0xfc, 0x8c, 0x76, 0x4a, 0xf7, 0x94, 0x7b, 0xd1, 0x01, 0xd4, 0xd6, 0xa1,
	0xcb, 0xcf, 0x70, 0x45, 0xc4, 0x77, 0xd6, 0xa1, 0x3b, 0x76, 0xd0, 0xf7, 0xd0, 0x28, 0xa7, 0x51,
	0x1c, 0xc7, 0xe6, 0xe0, 0xde, 0x3f, 0x4f, 0x32, 0xbe, 0x01, 0x1e, 0xfd, 0x29, 0x41, 0x3b, 0xf3,
	0x5e, 0x86, 0x2e, 0xef, 0xc8, 0xe7, 0xe7, 0xf1, 0x00, 0x1a, 0xa2, 0xeb, 0xfc, 0x68, 0x89, 0x54,
	0x5a, 0x58, 0xe1, 0x0e, 0x7e, 0xf2, 0x78, 0x30, 0xbb, 0x50, 0xbc, 0x77, 0x59, 0x36, 0xd5, 0xec,
	0x22, 0x30, 0xbd, 0x77, 0xf4, 0x76, 0xaa, 0xf2, 0x67, 0xa6, 0x8a, 0xbe, 0x82, 0xb6, 0x90, 0x8c,
	0xe9, 0x1b, 0x2f, 0xe1, 0x53, 0x56, 0x13, 0xb2, 0x2d, 0xee, 0xc4, 0xb9, 0x0f, 0x1d, 0x82, 0x72,
	0x4d, 0x53, 0x7b, 0xe5, 0x05, 0x4c, 0xab, 0x8b, 0x9c, 0xea, 0xd7, 0x34, 0x1d, 0x79, 0x01, 0x9b,
	0xc8, 0xca, 0x8e, 0x5a, 0x3b, 0xfa, 0xab, 0x2c, 0xf8, 0x8a, 0x44, 0xff, 0x63, 0xc1, 0xff, 0xad,
	0xa6, 0x03, 0xa8, 0xf9, 0x24, 0xe2, 0xbd, 0xdc, 0xc9, 0x7a, 0xe9, 0x93, 0x68, 0xec, 0xf0, 0x3b,
	0x84, 0xbb, 0xb7, 0x2a, 0x6d, 0xfa, 0x24, 0x2a, 0x0b, 0x7d, 0x0c, 0x8a, 0x4f, 0x19, 0x71, 0x08,
	0x23, 0xa2, 0xd0, 0x8f, 0x1d, 0xf1, 0x12, 0x35, 0x91, 0x95, 0xaa, 0x2a, 0x3f, 0x1a, 0x42, 0x3b,
	0xef, 0xf4, 0x59, 0x18, 0xfb, 0x84, 0xa1, 0x07, 0x70, 0xff, 0x72, 0x76, 0x6e, 0xe3, 0xd9, 0xcc,
	0xb2, 0xcf, 0x66, 0xf8, 0x4a, 0xb7, 0xec, 0x9f, 0xa6, 0x17, 0xd3, 0xd9, 0xcf, 0x53, 0xf5, 0x0e,
	0xba, 0x07, 0x68, 0x3b, 0xf8, 0xf2, 0x89, 0x2a, 0x71, 0x95, 0xfc, 0xf1, 0xdd, 0xa8, 0x5c, 0xe9,
	0xf3, 0x8f, 0xab, 0x6c, 0x07, 0x85, 0xca, 0xaf, 0x12, 0xb4, 0xde, 0xbf, 0xf2, 0xd1, 0x21, 0x1c,
	0xe4, 0x2c, 0x7b, 0xa4, 0x9b, 0x23, 0xdb, 0xb4, 0xb0, 0x6e, 0x19, 0xe7, 0xaf, 0xd4, 0x3b, 0x08,
	0x41, 0x07, 0x9f, 0x9d, 0x3e, 0xfb, 0xe1, 0xd9, 0xc0, 0x36, 0x47, 0xfa, 0xe0, 0xe9, 0x33, 0x55,
	0x42, 0xfb, 0xb0, 0x6b, 0x19, 0xa6, 0x65, 0x73, 0x71, 0x8e, 0x37, 0xb0, 0x5a, 0xe1, 0x1a, 0xb3,
	0x17, 0x13, 0xe3, 0xd4, 0xb2, 0xb7, 0xf0, 0x55, 0x74, 0x00, 0x7b, 0xa7, 0xb3, 0xe9, 0xf8, 0xc2,
	0xe4, 0xae, 0xa7, 0x4f, 0x06, 0x36, 0x77, 0xcb, 0x8f, 0x7e, 0x97, 0xa0, 0x51, 0xbe, 0xe1, 0x78,
	0xb2, 0x45, 0x0e, 0x16, 0x36, 0x0c, 0xdb, 0xb4, 0x74, 0xcb, 0x50, 0xef, 0x20, 0x80, 0x9a, 0x7e,
	0x6a, 0x8d, 0x5f, 0x1a, 0xaa, 0xc4, 0xd7, 0x67, 0x78, 0xf6, 0xda, 0x98, 0xaa, 0x15, 0xf4, 0x10,
	0xee, 0x0f, 0x8d, 0x39, 0x36, 0x4e, 0x75, 0xcb, 0x18, 0xda, 0xe6, 0xec, 0xcc, 0xb2, 0x87, 0xc6,
	0xa5, 0x61, 0x19, 0x43, 0xb5, 0xda, 0xad, 0x28, 0xd2, 0x16, 0x60, 0xa4, 0xe3, 0x61, 0x09, 0x90,
	0x05, 0xa0, 0x05, 0xca, 0x10, 0xeb, 0xe3, 0xe9, 0x78, 0x7a, 0xae, 0xee, 0x3c, 0x3a, 0x07, 0xa5,
	0x78, 0x77, 0xf2, 0x84, 0x6f, 0xe5, 0x62, 0xbd, 0x9a, 0xf3, 0x54, 0xea, 0x50, 0xbd, 0x9c, 0x9d,
	0xab, 0x12, 0x5f, 0x5c, 0xe9, 0x73, 0xb5, 0xc2, 0x9f, 0xce, 0x1c, 0x1b, 0x33, 0x3c, 0x34, 0xb0,
	0x31, 0xb4, 0x79, 0xb0, 0xfa, 0x62, 0x04, 0x87, 0xcb, 0xd0, 0x2f, 0x86, 0xe2, 0xf6, 0xe7, 0xca,
	0x8b, 0xb6, 0x95, 0xdb, 0x73, 0x6e, 0xce, 0xa5, 0xd7, 0x5d, 0xd7, 0x63, 0xab, 0xcd, 0xa2, 0xbf,
	0x0c, 0xfd, 0x93, 0xfc, 0x7b, 0xa2, 0xa0, 0x2c, 0x6a, 0x82, 0xf3, 0xdd, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x00, 0xc9, 0xa2, 0x26, 0xf4, 0x08, 0x00, 0x00,
}
