apiVersion: apps/v1
kind: Deployment
metadata:
  name: trillian-etcd-operator
  # Cluster-wide etcd-operator, so should always be in default namespace.
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: trillian-etcd-operator
  template:
    metadata:
      labels:
        name: trillian-etcd-operator
    spec:
      containers:
      - name: trillian-etcd-operator
        image: quay.io/coreos/etcd-operator:v0.9.4
        command:
        - etcd-operator
        - -cluster-wide
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
