apiVersion: v1
kind: Service
metadata:
  name: trillian-etcd-service
spec:
  type: NodePort
  selector:
    etcd_cluster: trillian-etcd-cluster
    app: etcd
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379
      nodePort: 32379
