apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: trillian-map-service
  name: trillian-map-service
spec:
  clusterIP: None
  ports:
  - name: grpclb
    port: 8090
    targetPort: 8090
  - name: metrics
    port: 8091
    targetPort: 8091
  selector:
    io.kompose.service: trillian-map
status:
  loadBalancer: {}
