version: '3.1'

services:
  db:
    image: ${MYSQLD_IMAGE:-mysql:8.0}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'bananas'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'zaphod'
