version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'bananas'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'zaphod'
    ports:
      - '3306:3306'
    expose:
      - '3306'

networks:
  default:
    external:
      name: cloudbuild