-- Caution - this removes all tables in our schema

DROP TABLE IF EXISTS Unsequenced;
DROP TABLE IF EXISTS Subtree;
DROP TABLE IF EXISTS SequencedLeafData;
DROP TABLE IF EXISTS TreeHead;
DROP TABLE IF EXISTS LeafData;
DROP TABLE IF EXISTS MapLeaf;
DROP TABLE IF EXISTS MapHead;
DROP TABLE IF EXISTS TreeControl;
DROP TABLE IF EXISTS MapHead;
DROP TABLE IF EXISTS MapLeaf;
DROP TABLE IF EXISTS Trees;
